import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {registerHooks} from 'node:module';
import {readFileSync} from 'node:fs';
import {newCharacter} from '../lib/model.ts';
const db=new DatabaseSync(':memory:');
db.exec(readFileSync(new URL('../drizzle/0000_green_mojo.sql',import.meta.url),'utf8'));
globalThis.testDB={prepare(sql){let values=[];const query={bind(...v){values=v;return query},async first(){return db.prepare(sql).get(...values)||null},async all(){return {results:db.prepare(sql).all(...values)}},async run(){const r=db.prepare(sql).run(...values);return {meta:{changes:Number(r.changes)}}}};return query;}};
registerHooks({resolve(specifier,context,next){if(specifier==='@/db')return {url:'data:text/javascript,export function getDB(){return globalThis.testDB}',shortCircuit:true};if(specifier==='@/lib/character-store')return {url:new URL('../lib/character-store.ts',import.meta.url).href,shortCircuit:true};return next(specifier,context)}});
const list=await import('../app/api/characters/route.ts');
const item=await import('../app/api/characters/[id]/route.ts');
const request=(method,body,user='owner-a',origin='https://ledger.example')=>new Request('https://ledger.example/api/characters',{method,headers:{'Content-Type':'application/json',...(user?{'oai-authenticated-user-id':user}:{}),origin},...(body?{body:JSON.stringify(body)}:{})});
let id,revision;
test('unauthenticated character requests are refused',async()=>{assert.equal((await list.GET(request('GET',null,''))).status,401)});
test('create, list, reload, edit and reload retain full character state',async()=>{const data=newCharacter('Wizard');data.notes='Saved campaign note';const result=await list.POST(request('POST',{data}));assert.equal(result.status,201);({id,revision}=await result.json());const ctx={params:Promise.resolve({id})};const loaded=await (await item.GET(request('GET'),ctx)).json();assert.deepEqual(loaded.data,data);assert.equal((await (await list.GET(request('GET'))).json()).characters.length,1);data.hp=7;const updated=await item.PUT(request('PUT',{data,revision}),ctx);assert.equal(updated.status,200);revision=(await updated.json()).revision;assert.equal(revision,2);assert.equal((await (await item.GET(request('GET'),ctx)).json()).data.hp,7);});
test('another user cannot list, read, overwrite or delete a character',async()=>{const ctx={params:Promise.resolve({id})};assert.deepEqual((await (await list.GET(request('GET',null,'owner-b'))).json()).characters,[]);assert.equal((await item.GET(request('GET',null,'owner-b'),ctx)).status,404);assert.equal((await item.PUT(request('PUT',{data:newCharacter(),revision},'owner-b'),ctx)).status,409);assert.equal((await item.DELETE(request('DELETE',{revision},'owner-b'),ctx)).status,409)});
test('stale revisions cannot overwrite newer edits',async()=>{const ctx={params:Promise.resolve({id})};assert.equal((await item.PUT(request('PUT',{data:newCharacter(),revision:1}),ctx)).status,409);assert.equal((await (await item.GET(request('GET'),ctx)).json()).data.hp,7)});
test('invalid character data and cross-origin writes are rejected',async()=>{assert.equal((await list.POST(request('POST',{data:{name:'Incomplete'}}))).status,400);assert.equal((await list.POST(request('POST',{data:newCharacter()},'owner-a','https://other.example'))).status,403);});
test('delete removes only the selected owned revision',async()=>{const ctx={params:Promise.resolve({id})};assert.equal((await item.DELETE(request('DELETE',{revision} ),ctx)).status,200);assert.equal((await item.GET(request('GET'),ctx)).status,404);assert.deepEqual((await (await list.GET(request('GET'))).json()).characters,[])});
