'use client';
import {useState} from 'react';
import {abilityKeys,abilityNames} from '@/lib/model';
import {advancementChoices,recordAdvancementChoice} from '@/lib/advancement-choices';
import {Btn,Choice,type SheetProps} from './sheet-ui';
export function AdvancementReminders({c,edit,openFeats}:Pick<SheetProps,'c'|'edit'>&{openFeats:()=>void}){
 const [selected,setSelected]=useState<Record<string,string>>({});const rows=advancementChoices(c),pending=rows.filter(r=>!r.choice),abilities=pending.filter(r=>r.kind==='ability').length,feats=pending.length-abilities;
 return <details className="advancement-reminders"><summary><span role="status">{pending.length?`Advancement choices pending: ${abilities} ability increases · ${feats} feat selections`:'Advancement choices recorded'}</span></summary><p className="fine">Ability increases are earned every 4 Hit Dice; general feats at 1st and every 3rd. Recorded class levels determine eligibility. Level adjustment grants neither. For existing characters, record choices already made without adding them twice.</p><Btn onClick={openFeats}>Choose or add feats</Btn>{rows.map(row=>{const value=selected[row.key]||'STR';return <div className="subcard" key={row.key}><strong>{row.label}</strong>{row.kind==='ability'?row.choice?<p>Recorded: {abilityNames[row.choice as typeof abilityKeys[number]]} +1</p>:<><Choice label={row.label+' ability'} value={value} options={abilityKeys.map(a=>[a,abilityNames[a]])} onChange={v=>setSelected(s=>({...s,[row.key]:v}))}/><div className="button-row"><Btn disabled={c.scores[value as typeof abilityKeys[number]]>=100} onClick={()=>edit(d=>recordAdvancementChoice(d,row.key,value,true))}>Apply +1 to base score</Btn><Btn onClick={()=>edit(d=>recordAdvancementChoice(d,row.key,value))}>Already included in my score</Btn></div></>:<Choice label={row.label+' selection'} value={row.choice||'none'} options={[[ 'none','Choose a recorded feat'],...c.features.filter(f=>f.kind==='Feat'&&(!rows.some(r=>r.kind==='feat'&&r.choice===f.id)||row.choice===f.id)).map(f=>[f.id,f.name+(f.choice?' ('+f.choice+')':'')] as [string,string])]} onChange={v=>edit(d=>{if(v==='none')delete d.advancementChoices[row.key];else recordAdvancementChoice(d,row.key,v)})}/>}</div>})}<p className="fine">Check feat prerequisites and the allowed bonus-feat list before assigning a choice. Class-granted feats such as Scribe Scroll are separate. Ability selections record changes to base scores; later Intelligence increases do not retroactively grant skill points.</p></details>;
}
