'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Save,BookOpen,Dices,Download,Upload,ScrollText,Shield,Swords,Backpack,Feather,Plus} from 'lucide-react';
import {characterSchema,uid,type Character,type Spell,type Feat} from '@/lib/model';
import {sheetTotals,makeMacro,makeRequest,resetDaily,type Roll} from '@/lib/rules';
import {rollFormula,parseDiceFormula} from '@/lib/dice.mjs';
import {F,N,Choice,Check,Btn,type Edit} from './sheet-ui';
import {Overview,Combat,SkillsView,Gear,Notes} from './character-views';
import {Spellbook} from './spellbook';
import {Features} from './features';
import {Classes} from './classes';
import {Powers} from './powers';
import {Races} from './races';
import {activateAutomation,recompute} from '@/lib/automation';
import {Calculations} from './calculations';
import {ThemePicker} from './theme-picker';
import {NewCharacterDialog} from './new-character';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyContent} from '@/components/ui/empty';
import {characterApi} from '@/lib/character-client';
import {parseCharacterFile} from '@/lib/character-file';
import {assetUrl,browserStorage} from '@/lib/deployment';
declare global {interface Window {BarrowBeyond20?:{detected:boolean,send:(request:ReturnType<typeof makeRequest>)=>void}}}
type Saved={id:string,name:string,revision:number,updated_at:string};
type Journal={id:string,title:string,formula?:string,total?:number,detail:string,macro:string,place:string,time:string};
type Confirm={title:string,description:string,action:()=>void};
type LoadedCharacter=Saved&{data:Character};
const api=<T=Saved>(url:string,init?:RequestInit)=>characterApi<T>(url,init);
export default function CharacterSheet(){
 const [c,setC]=useState<Character|null>(null);
 const [savedText,setSavedText]=useState('');const [record,setRecord]=useState<Saved|null>(null);const [items,setItems]=useState<Saved[]>([]);
 const [loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[switching,setSwitching]=useState(false),[saveError,setSaveError]=useState('');
 const inFlight=useRef<Promise<boolean>|null>(null);const current=useRef(c);current.current=c;const recordRef=useRef<Saved|null>(null);const savedRef=useRef('');const switchLock=useRef(false);
 const [tab,setTab]=useState('overview'),[detected,setDetected]=useState(false),[destination,setDestination]=useState('practice'),[whisper,setWhisper]=useState(false);
 const [journal,setJournal]=useState<Journal[]>([]),[looseDice,setLooseDice]=useState('1d20'),[guide,setGuide]=useState(false),[confirmation,setConfirmation]=useState<Confirm|null>(null);
 const [newOpen,setNewOpen]=useState(false),[loadAttempt,setLoadAttempt]=useState(0);
 const [spells,setSpells]=useState<Spell[]>([]),[feats,setFeats]=useState<Feat[]>([]),[referenceError,setReferenceError]=useState('');const [referenceAttempt,setReferenceAttempt]=useState(0);
 const fileInput=useRef<HTMLInputElement>(null);
 const serialized=c?JSON.stringify(c):'';const dirty=loaded&&c!==null&&serialized!==savedText;
 const edit:Edit=useCallback(recipe=>{if(!loaded||switchLock.current)return;setC(prev=>{if(!prev)return prev;const next=structuredClone(prev);recipe(next);return recompute(next,prev)});setSaveError('');},[loaded]);
 const confirm=(title:string,description:string,action:()=>void)=>setConfirmation({title,description,action});
 useEffect(()=>{let live=true;(async()=>{try{const list=await api<{characters:Saved[]}>('/api/characters');if(!live)return;setItems(list.characters);if(list.characters.length){const result=await api<LoadedCharacter>('/api/characters/'+list.characters[0].id);if(!live)return;const parsed=characterSchema.parse(result.data);const original=JSON.stringify(parsed);const data=activateAutomation(parsed);setC(data);current.current=data;recordRef.current={...result,name:data.name};savedRef.current=original;setRecord(recordRef.current);setSavedText(savedRef.current);}else {savedRef.current=current.current?JSON.stringify(current.current):'';setSavedText(savedRef.current);}}catch(e){if(live){setSaveError(e instanceof Error?e.message:'Character loading failed.');savedRef.current=current.current?JSON.stringify(current.current):'';setSavedText(savedRef.current);}}finally{if(live)setLoaded(true);}})();return()=>{live=false};},[loadAttempt]);
 useEffect(()=>{let live=true;setReferenceError('');Promise.all([fetch(assetUrl('data/spells.json')).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Spell[]>}),fetch(assetUrl('data/feats.json')).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Feat[]>})]).then(([s,f])=>{if(live){setSpells(s);setFeats(f)}}).catch(()=>{if(live)setReferenceError('The reference library could not be loaded. Your character is still available.');});return()=>{live=false}},[referenceAttempt]);
 useEffect(()=>{const check=()=>setDetected(!!window.BarrowBeyond20?.detected);check();document.addEventListener('BarrowBridgeChanged',check);return()=>document.removeEventListener('BarrowBridgeChanged',check)},[]);
 const save=useCallback(async(forceNew=false):Promise<boolean>=>{
  if(inFlight.current)return inFlight.current;
  const data=current.current;if(!data)return true;const snapshot=JSON.stringify(data);
  const job=(async()=>{setBusy(true);setSaveError('');try{
   const parsed=characterSchema.safeParse(data);if(!parsed.success)throw new Error('Please check: '+parsed.error.issues.slice(0,3).map(x=>x.path.join('.')+' '+x.message).join('; '));
   const existing=forceNew?null:recordRef.current;const result=await api('/api/characters'+(existing?'/'+existing.id:''),{method:existing?'PUT':'POST',body:JSON.stringify({data:parsed.data,...(existing?{revision:existing.revision}:{})})});
   const row={...result,name:data.name};recordRef.current=row;savedRef.current=snapshot;setRecord(row);setSavedText(snapshot);setItems(prev=>[row,...prev.filter(x=>x.id!==row.id)]);return true;
  }catch(e){setSaveError(e instanceof Error?e.message:'Saving failed. Your edits remain on this page.');return false;}finally{setBusy(false)}})();
  inFlight.current=job;try{return await job}finally{inFlight.current=null}
 },[]);
 useEffect(()=>{if(!dirty||busy||switching||saveError)return;const timer=setTimeout(()=>{if(!switchLock.current)void save()},1000);return()=>clearTimeout(timer)},[dirty,serialized,busy,switching,saveError,save]);
 useEffect(()=>{if(!dirty)return;const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave)},[dirty]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();void save()}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[save]);
 async function flush(){if(inFlight.current&&!await inFlight.current)return false;if(current.current&&JSON.stringify(current.current)!==savedRef.current)return await save();return true;}
 async function loadCharacter(id:string){if(switchLock.current)return;switchLock.current=true;setSwitching(true);try{if(!await flush())return;const result=await api<LoadedCharacter>('/api/characters/'+id);const parsed=characterSchema.parse(result.data);const original=JSON.stringify(parsed);const data=activateAutomation(parsed);setC(data);current.current=data;savedRef.current=original;setSavedText(savedRef.current);recordRef.current={...result,name:data.name};setRecord(recordRef.current);setSaveError('');setJournal([]);}catch(e){setSaveError(e instanceof Error?e.message:'Loading failed.')}finally{switchLock.current=false;setSwitching(false)}}
 async function replaceWith(data:Character){data=activateAutomation(data);if(switchLock.current)return false;switchLock.current=true;setSwitching(true);try{if(!await flush())return false;setC(data);current.current=data;recordRef.current=null;savedRef.current='';setRecord(null);setSavedText('');setSaveError('');setJournal([]);setTab(data.psionics.length?'powers':data.casters.length?'spells':'classes');return true;}finally{switchLock.current=false;setSwitching(false)}}
 async function removeCharacter(){if(!record||switchLock.current)return;switchLock.current=true;setSwitching(true);try{if(inFlight.current&&!await inFlight.current)return;const deleting=recordRef.current;if(!deleting)return;await api('/api/characters/'+deleting.id,{method:'DELETE',body:JSON.stringify({revision:deleting.revision})});setItems(prev=>prev.filter(x=>x.id!==deleting.id));setC(null);current.current=null;savedRef.current='';recordRef.current=null;setSavedText('');setRecord(null);setSaveError('');setJournal([]);toast.success('Character deleted.');}catch(e){setSaveError(e instanceof Error?e.message:'Could not delete this character.')}finally{switchLock.current=false;setSwitching(false)}}
 function exportCharacter(){if(!c)return;const blob=new Blob([JSON.stringify({format:'barrow-ledger-character',version:1,exportedAt:new Date().toISOString(),data:c},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=(c.name.replace(/[^a-zA-Z0-9_-]+/g,'-')||'character')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importCharacter(file:File){try{if(file.size>1000000)throw new Error('Choose a Barrow Ledger character file smaller than 1 MB.');const data=parseCharacterFile(await file.text());if(await replaceWith(data))toast.success('Character imported. Saving it as a new character…');}catch(e){toast.error(e instanceof Error?e.message:'Could not read this file.')}finally{if(fileInput.current)fileInput.current.value=''}}
 function roll(r:Roll,override?:string):boolean {try{if(!loaded||switchLock.current)return false;
  if(r.formula)r={...r,formula:parseDiceFormula(r.formula).formula};const macro=makeMacro(r,c?.name||'Barrow Ledger',whisper);const place=override||destination;
  let result:{total?:number,detail:string}={detail:r.details||r.fields?.map(([k,v])=>k+': '+v).join(' · ')||'Spell card'};
  if(place==='roll20'){if(!window.BarrowBeyond20?.detected){toast.error('Enable Beyond20 for this site first. Open Roll20 setup for the steps.');setGuide(true);return false;}window.BarrowBeyond20.send(makeRequest(r,c?.name||'Barrow Ledger',window.location.href,whisper));result.detail='Handed to Beyond20. Check your Roll20 chat for the result.';}else if(r.formula)result=rollFormula(r.formula);
  setJournal(prev=>[{id:uid(),title:r.title,formula:r.formula,...result,macro,place:place==='roll20'?'Beyond20 handoff':'Practice',time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})},...prev].slice(0,40));toast.success(place==='roll20'?'Handed to Beyond20':r.title+(result.total!==undefined?' · '+result.total:' · card added'));return true;
 }catch(e){toast.error(e instanceof Error?e.message:'This roll could not be made.');return false;}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);toast.success('Roll20 macro copied.')}catch{toast.error('Clipboard access is unavailable. Expand the macro, then select and copy it.')}}
 const props=c?{c,edit,roll,confirm}:null;const t=c?sheetTotals(c):null;
 return <>
 <a href="#character" className="skip-link">Skip to character sheet</a>
 <header className="masthead"><a href={assetUrl('')} className="wordmark"><span className="brand-mark">B</span><strong>BARROW<br/>LEDGER</strong></a><div className="masthead-right"><ThemePicker/><span className="edition">3.5 ADVENTURER’S RECORD</span><Btn className="header-button" onClick={()=>setGuide(true)}>Roll20 setup</Btn></div></header>
 <main className={'workbench'+(!c?' empty-workbench':'')}><div className="sheet-column">
 {(c||items.length>0)&&<div className="character-toolbar"><div className="character-picker"><Choice label="Your characters" value={record?.id||'unsaved'} options={[...(!record?[[ 'unsaved',(c?.name||'Choose a character')+(c?' · new':'')] as [string,string]]:[]),...items.map(x=>[x.id,x.name] as [string,string])]} onChange={v=>{if(v!=='unsaved')void loadCharacter(v)}}/></div><Btn disabled={busy||switching||!loaded} onClick={()=>setNewOpen(true)}><Plus size={16}/> New</Btn><Btn className="save-button" disabled={!c||busy||switching||!loaded} onClick={()=>void save()}><Save size={16}/>{busy?'Saving…':'Save'}</Btn></div>}
 <div className="save-status" role="status">{switching?'Loading character…':!loaded?'Opening your ledger…':busy?'Saving character…':saveError?(c?'Not saved — your edits are still on this page.':'Could not open saved characters.'):dirty?'Changes waiting to save…':record?(browserStorage?'Saved in this browser':'Character saved'):c?'New character · saving shortly':'Create or import a character to begin'}</div>
 {browserStorage&&<p className="browser-save-note fine">Characters save in this browser on this device. Export backups before clearing browser data or moving to another device. Import a character exported from your original sheet to bring it here.</p>}
 {saveError&&<div className="error-box"><p>{saveError}</p><div className="button-row">{c?<><Btn onClick={()=>void save()} disabled={busy}>Retry save</Btn><Btn onClick={exportCharacter}>Export backup</Btn><Btn disabled={busy} onClick={()=>void save(true)}>Save as new character</Btn></>:<Btn disabled={switching||busy} onClick={()=>{setLoaded(false);setSaveError('');setLoadAttempt(n=>n+1)}}>Retry opening characters</Btn>}</div></div>}
 <article id="character" className="parchment" aria-busy={!loaded||switching}>
 {!loaded?<div className="loading-sheet"><Skeleton className="h-16 w-3/4"/><Skeleton className="h-44 w-full"/><Skeleton className="h-80 w-full"/></div>:c&&t&&props?<fieldset disabled={switching} className="sheet-fieldset">
 <div className="sheet-rule"><span>CHARACTER RECORD</span><span>LEVEL {c.level}</span></div>
 <div className="identity"><div className="identity-main"><F className="character-name" label="Character name" value={c.name} onChange={v=>edit(d=>{d.name=v})}/><p className="character-subtitle">{c.race} · {c.classes}</p></div><div className="character-seal"><strong>{t.ac}</strong><small>ARMOR CLASS</small></div></div>
 <div className="quick-vitals"><span><b>{c.hp}</b> / {c.maxHp} HP</span><span>Touch <b>{t.touch}</b></span><span>Flat-footed <b>{t.flat}</b></span><span><b>{c.speed}</b> ft.</span></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="sheet-tabs">{[['overview','Sheet',Shield],['race','Race',Feather],['classes','Classes',ScrollText],['combat','Combat',Swords],['skills','Skills',Dices],['spells','Spells',BookOpen],['powers','Powers',BookOpen],['gear','Gear',Backpack],['features','Feats',ScrollText],['calculations','Calculations',Dices],['notes','Notes',Feather]].map(([value,label,Icon])=>{const Glyph=Icon as typeof Shield;return <TabsTrigger key={String(value)} value={String(value)}><Glyph size={16}/>{String(label)}</TabsTrigger>})}</TabsList>
 <TabsContent value="overview"><Overview {...props}/></TabsContent><TabsContent value="race"><Races {...props}/></TabsContent><TabsContent value="classes"><Classes {...props}/></TabsContent><TabsContent value="powers"><Powers {...props}/></TabsContent><TabsContent value="combat"><Combat {...props}/></TabsContent><TabsContent value="skills"><SkillsView {...props}/></TabsContent><TabsContent value="spells"><Spellbook {...props} spells={spells} referenceError={referenceError} retry={()=>setReferenceAttempt(n=>n+1)}/></TabsContent><TabsContent value="gear"><Gear {...props}/></TabsContent><TabsContent value="features"><Features {...props} feats={feats}/>{referenceError&&<div className="error-box">{referenceError}<Btn onClick={()=>setReferenceAttempt(n=>n+1)}>Retry library</Btn></div>}</TabsContent><TabsContent value="calculations"><Calculations {...props}/></TabsContent><TabsContent value="notes"><Notes {...props}/></TabsContent>
 </Tabs><div className="sheet-bottom"><span>BARROW LEDGER</span><span>Keep a good record. Leave a legible corpse.</span></div>
 </fieldset>:<Empty className="ledger-empty"><EmptyHeader><EmptyTitle><h1>{items.length?'Open your next character':'Your ledger is ready'}</h1></EmptyTitle><EmptyDescription>{items.length?'Choose a saved character above, or start someone new.':'Create an adventurer or import a character you already have.'}</EmptyDescription></EmptyHeader><EmptyContent><div className="button-row"><Btn className="primary" disabled={busy||switching} onClick={()=>setNewOpen(true)}><Plus size={18}/> Create character</Btn><Btn disabled={busy||switching} onClick={()=>fileInput.current?.click()}><Upload size={18}/> Import character</Btn></div></EmptyContent></Empty>}
 </article>
 <input className="sr-only" type="file" accept=".json,application/json" ref={fileInput} onChange={e=>{const f=e.target.files?.[0];if(f)void importCharacter(f)}} aria-label="Import a Barrow Ledger character"/>
 {c&&<div className="file-actions"><Btn onClick={exportCharacter} disabled={!c||!loaded}><Download size={16}/> Export character</Btn><Btn onClick={()=>fileInput.current?.click()} disabled={!loaded||busy||switching}><Upload size={16}/> Import character</Btn>{record&&c&&<Btn className="quiet danger" disabled={busy||switching} onClick={()=>confirm('Delete '+c.name+'?','This permanently deletes this saved character. Export a backup first if you want to keep a copy.',()=>void removeCharacter())}>Delete character</Btn>}</div>}
 </div>
 {c&&<aside className="journal-column"><section className="desk-panel"><div className="desk-heading"><h2>At the table</h2><Dices size={22}/></div><Choice label="Roll destination" value={destination} options={[[ 'practice','Practice on this sheet'],['roll20','Roll20 through Beyond20']]} onChange={setDestination}/><p className="fine">{detected?'Beyond20 detected. Select your Roll20 game in the extension.':'Beyond20 not detected. Practice rolls work here.'}</p><Check label="Whisper Roll20 rolls to GM" checked={whisper} onChange={setWhisper}/><N label="Situational check modifier" value={c.situational} onChange={v=>edit(d=>{d.situational=v})}/><p className="fine">Applies to attacks, saves, skills, initiative, grapple, and ability checks.</p><div className="loose-dice"><F label="Loose dice" value={looseDice} onChange={setLooseDice} placeholder="2d6+3"/><Btn onClick={()=>roll({title:'Loose dice',formula:looseDice,details:'Custom roll; no sheet bonuses added.'})}>Roll</Btn></div><Btn className="wide" onClick={()=>confirm('Reset daily uses?','Restore spell slots, prepared copies, power points, and tracked daily features. Clear psionic focus. This does not restore hit points or change your preparations.',()=>edit(d=>{Object.assign(d,resetDaily(d))}))}>Reset daily uses</Btn></section>
 <section className="desk-panel roll-journal"><div className="desk-heading"><h2>Roll journal</h2>{journal.length>0&&<button className="text-button" onClick={()=>setJournal([])}>Clear</button>}</div><p className="fine journal-intro">{destination==='practice'?'Your practice rolls appear here.':'Results are rolled in Roll20; handoffs are recorded here.'}</p><div aria-live="polite" aria-relevant="additions">{journal.length===0?<div className="journal-empty"><Dices size={32}/><p>The dice await.</p><span>Choose an ability, weapon, skill, or spell to begin.</span></div>:journal.map(j=><article className="roll-entry" key={j.id}><div className="roll-entry-top"><span>{j.place}</span><time>{j.time}</time></div><h3>{j.title}</h3>{j.total!==undefined&&<div className="roll-total">{j.total}</div>}{j.formula&&<code className="roll-formula">{j.formula}</code>}<p>{j.detail}</p><button className="text-button" onClick={()=>void copy(j.macro)}>Copy Roll20 macro</button><details><summary>Show macro</summary><textarea aria-label={j.title+' Roll20 macro'} readOnly value={j.macro} rows={3} onFocus={e=>e.target.select()}/></details></article>)}</div></section>
 </aside>}</main>
 <footer className="site-footer"><span>3.5 SRD · {spells.length||606} spells</span><a href={assetUrl('data/OPEN-GAME-LICENSE.txt')} target="_blank" rel="noreferrer">Open Game License & credits</a><span>Independent Roll20 companion</span></footer>
 <Dialog open={guide} onOpenChange={setGuide}><DialogContent className="ledger-modal"><DialogHeader><DialogTitle>Take the sheet to Roll20</DialogTitle><DialogDescription>Use the Beyond20 browser extension in the same desktop browser as your Roll20 game.</DialogDescription></DialogHeader><ol className="setup-steps"><li><a href="https://beyond20.here-for-more.info/install" target="_blank" rel="noreferrer">Install Beyond20</a> for Chrome or Firefox.</li><li>In Beyond20’s advanced options, add this site to its custom domains and grant access:<code>{typeof window!=='undefined'?window.location.origin:'https://barrow-sheet-demo.clockworkkit.chatgpt.site'}/*</code></li><li>Refresh this sheet. If needed, click the extension icon to activate it on this page.</li><li>Open your Roll20 game in the same browser. Select that game as Beyond20’s destination.</li></ol><p className="connection-status">{detected?'Beyond20 detected on this sheet.':'Beyond20 has not announced itself on this sheet yet.'}</p><Btn className="primary" onClick={()=>{if(roll({title:'Connection test',formula:'1d20',details:'Barrow Ledger connection test.'},'roll20')){setDestination('roll20');toast.success('Test handed to Beyond20. Check your Roll20 chat.')}}}>Send test roll</Btn><p className="fine">The extension reports detection, but does not confirm delivery. Check Roll20 chat after the test. This sends rolls and cards; character attributes, tokens, HP, and the turn tracker are managed separately in Roll20.</p><p className="fine">Without the extension, make a practice roll and use Copy Roll20 macro, then paste into Roll20 chat. <a href="https://beyond20.here-for-more.info/api#integrating-with-beyond20" target="_blank" rel="noreferrer">Beyond20 integration guide</a></p></DialogContent></Dialog>
 <NewCharacterDialog open={newOpen} onOpenChange={setNewOpen} busy={busy||switching} onCreate={replaceWith}/>
 <AlertDialog open={!!confirmation} onOpenChange={v=>!v&&setConfirmation(null)}><AlertDialogContent className="ledger-modal"><AlertDialogHeader><AlertDialogTitle>{confirmation?.title}</AlertDialogTitle><AlertDialogDescription>{confirmation?.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{const action=confirmation?.action;setConfirmation(null);action?.()}}>Confirm</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Toaster position="bottom-right" richColors/>
 </>;
}
