'use client';
import {assetUrl} from '@/lib/deployment';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {classCatalog,findClass,classTotals,applyClassTotals,inferClassEntries,copyClassFeatures,makeCaster,makePsionic,type ClassDefinition} from '@/lib/classes';
import {uid} from '@/lib/model';
import {signed} from '@/lib/rules';
import {F,N,Choice,Btn,Section,Stat,type SheetProps} from './sheet-ui';
import {applyClericSpecialty} from '@/lib/cleric-specialty';
import {FactotumPanel} from './factotum-panel';
import type {Spell} from '@/lib/model';
import {toast} from 'sonner';
import {effectiveScore} from '@/lib/ancestry';
export function Classes({c,edit,confirm,roll,spells}:SheetProps&{spells:Spell[]}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState('all');const [detail,setDetail]=useState<ClassDefinition|null>(null);const [refs,setRefs]=useState<ClassDefinition[]>([]),[refError,setRefError]=useState('');
 const t=classTotals(c.classLevels,c.ancestry),inferred=inferClassEntries(c.classes);const matches=classCatalog.filter(d=>(kind==='all'||d.kind===kind)&&d.name.toLowerCase().includes(query.toLowerCase()));
 async function show(def:ClassDefinition){setDetail(def);if(refs.length)return;try{setRefError('');const res=await fetch(assetUrl('data/classes.json'));if(!res.ok)throw new Error();setRefs(await res.json() as ClassDefinition[])}catch{setRefError('Full class text could not be loaded. The progression table is available below.')}}
 function add(def:ClassDefinition){if(c.classLevels.some(x=>x.classId===def.id)){toast.error('That class is already recorded. Change its level on the sheet.');return}edit(d=>{d.classLevels.push({id:uid(),classId:def.id,name:def.name,level:1,notes:''})});setOpen(false);toast.success(def.name+' added. Totals now follow the recorded class levels.');}
 const reference=refs.find(d=>d.id===detail?.id)||detail;
 return <><Section title="Classes & advancement" action={<Btn onClick={()=>setOpen(true)}>+ Add class</Btn>}>
 <p className="muted">Record each class separately. Character level, base attack, saves, HP, hit dice and class-skill flags update automatically, including recorded racial Hit Dice.</p>
 {!c.classLevels.length&&<div className="empty-note"><p>Current class line: <strong>{c.classes||'None'}</strong></p><p>Add an entry for each of your current classes before applying totals.</p>{inferred.length>0&&<Btn className="primary" onClick={()=>edit(d=>{d.classLevels=inferred})}>Use current class line</Btn>}</div>}
 {c.classLevels.map((e,i)=>{const def=findClass(e.classId),row=def?.levels.find(x=>x.level===e.level);return <div className="subcard class-entry" key={e.id}><div className="row-head"><div><h3>{e.name}</h3><p className="fine">{def?.kind||'Custom'} · {def?'d'+def.hitDie+' · '+def.skillPoints+' + Int skill points per level':'Enter base statistics manually'}</p></div><N label="Class level" value={e.level} min={1} max={def?.levels.length||30} onChange={v=>edit(d=>{d.classLevels[i].level=v})}/></div>{row&&<div className="class-statline"><span>BAB <b>{signed(row.bab)}</b></span><span>Fort <b>{signed(row.fort)}</b></span><span>Ref <b>{signed(row.ref)}</b></span><span>Will <b>{signed(row.will)}</b></span></div>}{def?.kind==='Prestige'&&def.requirements&&<details><summary>Entry requirements</summary><p className="reference-text">{def.requirements}</p></details>}<F label="Choices & advancement notes" value={e.notes} onChange={v=>edit(d=>{d.classLevels[i].notes=v})} placeholder="Chosen feats, favored enemies, advanced casting class…"/><div className="button-row">{def&&<Btn onClick={()=>void show(def)}>Class reference</Btn>}{def&&row?.slots&&<Btn onClick={()=>{if(c.casters.some(p=>p.name===def.name)){toast.error('This class already has a spellcasting tradition. Adjust it in Spells.');return}const ability=def.id==='wizard'||def.id==='assassin'?'INT':['bard','sorcerer'].includes(def.id)?'CHA':'WIS';edit(d=>{d.casters.push(makeCaster(def,e.level,effectiveScore(c,ability)))});toast.success('Casting tradition added to Spells.')}}>Add casting tradition</Btn>}{def&&(def.kind==='Psionic'||row?.powerPoints!==undefined)&&<Btn onClick={()=>{if(c.psionics.some(p=>p.name===def.name)){toast.error('This tradition is already recorded in Powers.');return}const ability=def.id==='psion'?'INT':def.id==='wilder'?'CHA':'WIS';edit(d=>{d.psionics.push(makePsionic(def,e.level,effectiveScore(c,ability)))});toast.success('Psionic tradition added to Powers.')}}>Add psionic tradition</Btn>}<Btn className="quiet danger" onClick={()=>confirm('Remove '+e.name+'?','Remove this class entry and recalculate its totals. Existing spell choices remain recorded.',()=>edit(d=>{d.classLevels=d.classLevels.filter(x=>x.id!==e.id)}))}>Remove</Btn></div></div>})}
 {c.classLevels.length>0&&<><div className="stats class-totals"><Stat label="Total level" value={t.level}/><Stat label="Base attack" value={signed(t.bab)}/><Stat label="Fort / Ref / Will" value={[t.fort,t.ref,t.will].map(signed).join(' / ')}/></div>{t.missing.length>0&&<p className="error-text">Missing class table: {t.missing.join(', ')}. Enter totals manually.</p>}<div className="button-row"><Btn className="primary" disabled={c.automation.enabled||!!t.missing.length||t.level>100} onClick={()=>confirm('Apply these class totals?',`Level ${t.level}; BAB ${signed(t.bab)}; base saves ${signed(t.fort)} / ${signed(t.ref)} / ${signed(t.will)}; hit dice ${t.hitDice}. These replace the corresponding base fields and class-skill flags.`,()=>{edit(d=>applyClassTotals(d));toast.success('Class totals applied.')})}>{c.automation.enabled?"Totals update automatically":"Apply class totals"}</Btn><Btn onClick={()=>{edit(d=>copyClassFeatures(d));toast.success('Class feature summaries added to Feats.')}}>Add / update class features</Btn></div></>}
 <p className="fine">Totals use ordinary multiclass rules: each class’s base attack and saves are added separately. For gestalt or fractional progressions, enter your own totals. Calculations controls HP methods, spell progression, skill budgets and house-rule overrides. Skill ranks and advancement choices are yours to assign.</p>
 </Section>{c.classLevels.some(e=>e.classId==='cleric')&&<Section title="Cleric specialty"><Choice label="Cleric specialty" value={c.clericSpecialty} onChange={v=>edit(d=>applyClericSpecialty(d,v as typeof d.clericSpecialty))} options={[['none','Standard cleric'],['axe-brother','Axe Brother of Clangeddin']]}/><p className="fine">Axe Brothers retain normal cleric progression and gain Silverbeard as a first-level cleric spell. Prepare it in Spells. Changing specialty preserves recorded spells and spent uses.</p></Section>}<FactotumPanel c={c} edit={edit} roll={roll} confirm={confirm} spells={spells}/><Section title="Class library" note="11 core · 4 psionic · Factotum · 24 prestige classes"><div className="button-row"><Btn onClick={()=>{setKind('Core');setOpen(true)}}>Core classes</Btn><Btn onClick={()=>{setKind('Psionic');setOpen(true)}}>Psionic classes</Btn><Btn onClick={()=>{setKind('Supplemental');setOpen(true)}}>Supplemental classes</Btn><Btn onClick={()=>{setKind('Prestige');setOpen(true)}}>Prestige classes</Btn></div><p className="fine">Check prestige requirements before adding levels. Eligible casting advancement follows linked traditions; choose between multiple traditions in Calculations.</p><details><summary>Use a class from another book</summary><p className="fine">Keep the book’s class name, levels, and features here, and enter its statistics manually.</p><Btn onClick={()=>edit(d=>{d.classLevels.push({id:uid(),classId:'custom-'+uid(),name:'Custom class',level:1,notes:''})})}>+ Custom class</Btn>{c.classLevels.filter(e=>e.classId.startsWith('custom-')).map(e=><F key={e.id} label="Custom class name" value={e.name} onChange={v=>edit(d=>{d.classLevels.find(x=>x.id===e.id)!.name=v})}/>)}</details></Section>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="ledger-modal library-modal"><DialogHeader><DialogTitle>Choose a class</DialogTitle><DialogDescription>Base classes and familiar SRD prestige classes. Read the entry requirements before adding a prestige level.</DialogDescription></DialogHeader><div className="fields two"><F label="Find a class" value={query} onChange={setQuery} placeholder="Rogue, Mystic Theurge, Slayer…"/><Choice label="Class type" value={kind} onChange={setKind} options={[[ 'all','All classes'],['Core','Core base classes'],['Psionic','Psionic base classes'],['Prestige','Prestige classes'],['Supplemental','Supplemental base classes']]}/></div><div className="catalog-list">{matches.map(d=><div className="catalog-row" key={d.id}><div><button className="spell-title" onClick={()=>void show(d)}>{d.name}</button><p className="fine">{d.kind} · d{d.hitDie} · {d.skillPoints} + Int skills · {d.levels.length} levels</p></div><Btn disabled={c.classLevels.some(e=>e.classId===d.id)} onClick={()=>add(d)}>{c.classLevels.some(e=>e.classId===d.id)?'Added':'+ Add'}</Btn></div>)}{!matches.length&&<p className="empty-note">No classes match your search.</p>}</div></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="ledger-modal reference-modal"><DialogHeader><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.kind} class · d{detail?.hitDie} Hit Die · {detail?.skillPoints} + Int skill points per level</DialogDescription></DialogHeader>{reference&&<><p className="fine">{reference.alignment}</p>{reference.requirements&&<details open><summary>Entry requirements</summary><p className="reference-text">{reference.requirements}</p></details>}<details><summary>Class skills</summary><p>{reference.skills}</p></details><Table className="class-table"><TableHeader><TableRow>{['Level','BAB','Fort','Ref','Will','Features / advancement'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{reference.levels.map(r=><TableRow key={r.level}><TableCell>{r.level}</TableCell><TableCell>{signed(r.bab)}</TableCell><TableCell>{signed(r.fort)}</TableCell><TableCell>{signed(r.ref)}</TableCell><TableCell>{signed(r.will)}</TableCell><TableCell><span>{r.special}</span>{r.extra.some(x=>/level of existing/i.test(x))&&<p className="fine">{r.extra.filter(x=>/level of existing/i.test(x)).join('; ')}</p>}{r.powerPoints!==undefined&&<p className="fine">{r.powerPoints} base PP · {r.powersKnown} powers known · max power level {r.powerLevel}</p>}{r.slots&&<p className="fine">Base slots {r.slots.map((n,i)=>n==null?null:`${i}: ${n}`).filter(Boolean).join(' · ')}{reference.id==='cleric'?' · +1 domain slot per available spell level above 0':''}</p>}</TableCell></TableRow>)}</TableBody></Table><details><summary>Full class rules</summary>{refError?<p className="error-text">{refError} <Btn onClick={()=>void show(reference)}>Retry</Btn></p>:<p className="reference-text">{reference.description||'Loading class reference…'}</p>}</details><a className="source-link" href={reference.source} target="_blank" rel="noreferrer">Read the class source</a></>}</DialogContent></Dialog>
 </>;
}
