'use client';
import {useId,useState} from 'react';
import {abilityKeys,uid} from '@/lib/model';
import {creatureTypes,naturalAttackSchema,type CreatureProfile,type NaturalAttack} from '@/lib/creature-schema';
import {naturalAttackRoutine,racialCreatureStatistics} from '@/lib/creatures';
import {challengeRatingLabel} from '@/lib/bestiary';
import {F,N,Choice,Check,Btn,Section,type SheetProps} from './sheet-ui';

function ListField({label,values,onChange}:{label:string,values:string[],onChange:(v:string[])=>void}){
 const id=useId(),[text,setText]=useState(values.join('; '));
 return <label htmlFor={id} className="field"><span>{label} (separate with semicolons)</span><textarea id={id} value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{const next=[...new Set(text.split(';').map(s=>s.trim()).filter(Boolean))];onChange(next);setText(next.join('; '))}} rows={2}/></label>;
}
export function CreatureEditor({c,edit,confirm}:SheetProps){
 const p=c.creature;if(!p)return null;
 const set=(patch:Partial<CreatureProfile>)=>edit(d=>{Object.assign(d.creature!,patch)});
 const source=/^https?:\/\//i.test(p.source)?p.source:null;
 let suggested:ReturnType<typeof racialCreatureStatistics>|null=null;try{suggested=racialCreatureStatistics(c)}catch{/* Keep unfinished edits visible for correction. */}
 return <>
 <Section title="Creature record" note="Edit the printed statistics directly. Changing type or Hit Dice does not silently advance this creature.">
 <div className="fields three"><Choice label="Creature type" value={p.type} options={[...creatureTypes]} onChange={v=>set({type:v as CreatureProfile['type']})}/><Choice label="Challenge rating" value={p.challengeRating===null?'unknown':String(p.challengeRating)} options={[[ 'unknown','Unrated'],...[1/8,1/6,1/4,1/3,1/2,...Array.from({length:101},(_,i)=>i),...(p.challengeRating!==null?[p.challengeRating]:[])].filter((v,i,a)=>a.indexOf(v)===i).map(v=>[String(v),challengeRatingLabel(v)] as [string,string])]} onChange={v=>set({challengeRating:v==='unknown'?null:Number(v)})}/><N label="Racial HD" value={p.racialHitDice} min={0} max={100} step={.25} onChange={v=>{const hd=[.25,.5].includes(v)?v:Math.floor(v);edit(d=>{d.creature!.racialHitDice=hd;d.level=Math.max(1,Math.ceil(hd)+d.classLevels.reduce((sum,row)=>sum+row.level,0))})}}/><Choice label="Racial die" value={String(p.hitDie)} options={[4,6,8,10,12].map(n=>[String(n),'d'+n])} onChange={v=>set({hitDie:Number(v) as CreatureProfile['hitDie']})}/><N label="Space (ft.)" value={p.space} min={0} max={10000} step={.5} onChange={v=>set({space:v})}/><N label="Reach (ft.)" value={p.reach} min={0} max={10000} step={.5} onChange={v=>set({reach:v})}/></div>
 <ListField key={'subtypes-'+c.name} label="Subtypes" values={p.subtypes} onChange={v=>set({subtypes:v})}/>
 <details><summary>Racial progression reference</summary><div className="button-row">{(['fort','ref','will'] as const).map(s=><Check key={s} label={'Good '+s+' save'} checked={p.goodSaves.includes(s)} onChange={v=>set({goodSaves:v?[...p.goodSaves,s]:p.goodSaves.filter(x=>x!==s)})}/>)}</div>{suggested&&<p>Racial-only defaults: BAB {suggested.bab}; Fort {suggested.saves.fort}, Ref {suggested.saves.ref}, Will {suggested.saves.will}; average HP {suggested.averageHp??'enter printed HP'}.</p>}<Btn disabled={!!c.classLevels.length||!p.racialHitDice||!suggested||suggested.averageHp===null} onClick={()=>confirm('Apply racial defaults?','Replace BAB, base saves and maximum HP with racial defaults. Current injuries are retained. Printed exceptions and feat bonuses may need to be re-entered.',()=>edit(d=>{const stats=racialCreatureStatistics(d);if(stats.averageHp===null)return;const injury=d.maxHp-d.hp;d.bab=stats.bab;d.maxHp=stats.averageHp;d.hp=d.maxHp-injury;for(const s of ['fort','ref','will'] as const)d.saves[s].base=stats.saves[s];d.hitDice=d.creature!.racialHitDice+'d'+d.creature!.hitDie;}))}>Apply racial defaults</Btn></details>
 <div className="fields four">{(['burrow','climb','swim','fly'] as const).map(mode=><N key={mode} label={mode+' speed (ft.)'} value={p.movement[mode]} min={0} max={10000} onChange={v=>set({movement:{...p.movement,[mode]:v}})}/>)}</div><Choice label="Flight maneuverability" value={p.movement.maneuverability??'none'} options={['none','perfect','good','average','poor','clumsy']} onChange={v=>set({movement:{...p.movement,maneuverability:v==='none'?null:v as CreatureProfile['movement']['maneuverability']}})}/>
 <F label="Senses" value={p.senses} onChange={v=>set({senses:v})}/><div className="fields two"><F label="Immunities" value={p.immunities} onChange={v=>set({immunities:v})}/><F label="Vulnerabilities" value={p.vulnerabilities} onChange={v=>set({vulnerabilities:v})}/></div>
 <ListField key={'attacks-'+c.name} label="Special attacks" values={p.specialAttacks} onChange={v=>set({specialAttacks:v})}/><ListField key={'qualities-'+c.name} label="Special qualities" values={p.specialQualities} onChange={v=>set({specialQualities:v})}/>
 <F label="Special ability rules / exceptions" value={p.notes} area onChange={v=>set({notes:v})}/>
 <details><summary>Ecology and source</summary>{(['environment','organization','treasure','advancement','source'] as const).map(key=><F key={key} label={key[0].toUpperCase()+key.slice(1)} value={p[key]} onChange={v=>set({[key]:v})}/>)}</details>{source&&<p><a href={source} target="_blank" rel="noreferrer">Creature source ↗</a></p>}
 </Section></>;
}
export function NaturalAttacks({c,edit,roll,confirm}:SheetProps){
 const [mixed,setMixed]=useState(false);if(!c.creature)return null;
 let routine:ReturnType<typeof naturalAttackRoutine>=[],error='';try{routine=naturalAttackRoutine(c,{withManufacturedWeapon:mixed})}catch{error='Finish the attack name, count and damage dice to enable its rolls.';}
 const update=(id:string,patch:Partial<NaturalAttack>)=>edit(d=>{Object.assign(d.creature!.naturalAttacks.find(a=>a.id===id)!,patch)});
 return <Section title="Natural attacks" note="Roll one attack at a time. Use only available limbs; natural weapons do not gain BAB iteratives." action={<Btn disabled={c.creature.naturalAttacks.length>=50} onClick={()=>edit(d=>{d.creature!.naturalAttacks.push(naturalAttackSchema.parse({id:uid(),name:'Claw'}))})}>+ Natural attack</Btn>}>
 <Check label="Used alongside a manufactured weapon (all natural attacks secondary)" checked={mixed} onChange={setMixed}/>{error&&<p role="alert" className="error-box">{error}</p>}
 {c.creature.naturalAttacks.map(a=><div className="subcard" key={a.id}><div className="row-head"><F label="Natural weapon" value={a.name} onChange={v=>update(a.id,{name:v})}/><Btn onClick={()=>confirm('Remove '+a.name+'?','Remove this natural weapon from the sheet.',()=>edit(d=>{d.creature!.naturalAttacks=d.creature!.naturalAttacks.filter(x=>x.id!==a.id)}))}>Remove</Btn></div><div className="fields four"><N label="Number of attacks" value={a.count} min={1} max={50} onChange={v=>update(a.id,{count:Math.floor(v)})}/><Choice label="Role" value={a.role} options={['primary','secondary']} onChange={v=>update(a.id,{role:v as NaturalAttack['role']})}/><Choice label="Attack ability" value={a.ability} options={[...abilityKeys]} onChange={v=>update(a.id,{ability:v as NaturalAttack['ability']})}/><F label="Damage dice" value={a.damage} onChange={v=>update(a.id,{damage:v})}/><N label="Attack adjustment" value={a.attackBonus} onChange={v=>update(a.id,{attackBonus:v})}/><N label="Damage adjustment" value={a.damageBonus} onChange={v=>update(a.id,{damageBonus:v})}/><Choice label="Strength multiplier" value={String(a.strengthMultiplier)} options={['0','0.5','1','1.5']} onChange={v=>update(a.id,{strengthMultiplier:Number(v) as NaturalAttack['strengthMultiplier']})}/><N label="Critical threat from" value={a.criticalRange} min={2} max={20} onChange={v=>update(a.id,{criticalRange:Math.floor(v)})}/><N label="Critical multiplier" value={a.criticalMultiplier} min={2} max={10} onChange={v=>update(a.id,{criticalMultiplier:Math.floor(v)})}/></div><div className="button-row">{(['bludgeoning','piercing','slashing'] as const).map(t=><Check key={t} label={t} checked={a.damageTypes.includes(t)} onChange={v=>update(a.id,{damageTypes:v?[...a.damageTypes,t]:a.damageTypes.filter(x=>x!==t)})}/>)}</div><F label="Attack notes" value={a.notes} onChange={v=>update(a.id,{notes:v})}/><div className="button-row">{routine.filter(r=>r.id.startsWith(a.id+':')).map((r,i)=><Btn key={r.id} onClick={()=>roll({title:r.name+' '+(i+1),formula:r.attackFormula,details:r.role+' attack; threat '+r.criticalRange+'–20 / ×'+r.criticalMultiplier+'. '+r.notes})}>Attack {i+1}: {r.attackBonus>=0?'+':''}{r.attackBonus}</Btn>)}{routine.find(r=>r.id===a.id+':0')&&<Btn onClick={()=>{const r=routine.find(r=>r.id===a.id+':0')!;roll({title:a.name+' damage',formula:r.damageFormula,details:r.damageTypes.join(', ')+'. '+r.notes})}}>Damage</Btn>}</div></div>)}
 {!c.creature.naturalAttacks.length&&<p>No natural attacks recorded. Manufactured weapons are below.</p>}</Section>;
}
