'use client';
import {useState} from 'react';
import type {Spell} from '@/lib/model';
import {factotumNumbers,spendInspiration,chooseDilettante,dilettanteProblem,useDilettante} from '@/lib/factotum';
import {skillBonus,signed} from '@/lib/rules';
import {Section,Stat,N,F,Btn,Choice,type SheetProps} from './sheet-ui';
export function FactotumPanel({c,edit,roll,confirm,spells}:SheetProps&{spells:Spell[]}){
 const [query,setQuery]=useState(''),[skillId,setSkillId]=useState('');const n=factotumNumbers(c);if(!n.level)return null;
 const skill=c.skills.find(s=>s.id===skillId),eligible=spells.filter(s=>!dilettanteProblem(c,s)&&s.name.toLowerCase().includes(query.toLowerCase()));
 const spend=(cost:number)=>edit(d=>spendInspiration(d,cost));
 return <Section title="Factotum" note="Dungeonscape, pp. 14–17"><div className="stats"><Stat label="Inspiration remaining" value={`${n.remaining} / ${n.inspiration}`}/><Stat label="Daily spell choices" value={`${c.factotum.spells.length} / ${n.spells}`}/></div><div className="fields two"><N label="Extra inspiration (feats / house rules)" min={0} value={c.factotum.inspirationExtra} onChange={v=>edit(d=>{d.factotum.inspirationExtra=v})}/><N label="Inspiration spent" min={0} max={n.inspiration} value={c.factotum.spent} onChange={v=>edit(d=>{d.factotum.spent=v})}/></div><Btn onClick={()=>edit(d=>{d.factotum.spent=0})}>New encounter: restore inspiration</Btn><p className="fine">An encounter reset preserves daily uses and spent spells. Brains over Brawn (level 3) and Improved Cunning Defense (level 16, light or no armor) apply automatically when calculations are enabled. Target-specific and one-roll bonuses below require manual application.</p>
 <div className="button-row"><Btn disabled={n.remaining<1} onClick={()=>spend(1)}>Cunning Insight: spend 1</Btn>{n.level>=3&&<Btn disabled={n.remaining<1} onClick={()=>spend(1)}>Cunning Defense: spend 1</Btn>}{n.level>=4&&<Btn disabled={n.remaining<1} onClick={()=>spend(1)}>Cunning Strike: spend 1</Btn>}{n.level>=8&&<Btn disabled={n.remaining<3} onClick={()=>spend(3)}>Cunning Surge: spend 3</Btn>}{n.level>=11&&<Btn disabled={n.remaining<2} onClick={()=>spend(2)}>Cunning Breach: spend 2</Btn>}{n.level>=13&&<Btn disabled={n.remaining<4||c.factotum.dodgeUsed} onClick={()=>edit(d=>{spendInspiration(d,4);d.factotum.dodgeUsed=true})}>Cunning Dodge: spend 4 (once/day)</Btn>}{n.level>=19&&<Btn disabled={n.remaining<4} onClick={()=>spend(4)}>Cunning Brilliance: spend 4</Btn>}</div><p className="fine">Record Brilliance’s three selected features and their individual daily uses in class notes. Consult the class source for action timing and prerequisites.</p>
 <h3>Cunning Knowledge</h3><Choice label="Trained skill" value={skillId||'none'} options={[[ 'none','Choose a skill'],...c.skills.filter(s=>s.ranks>=1).map(s=>[s.id,s.name] as [string,string])]} onChange={setSkillId}/><Btn disabled={!skill||n.remaining<1||c.factotum.knowledgeUsed.includes(skillId)} onClick={()=>{if(skill&&roll({title:skill.name+' — Cunning Knowledge',formula:'1d20'+signed(skillBonus(c,skill)+n.level),details:`Includes +${n.level} Cunning Knowledge.`}))edit(d=>{spendInspiration(d,1);d.factotum.knowledgeUsed.push(skillId)})}}>Roll with Knowledge (1 inspiration, once/day per skill)</Btn>
 {n.level>=5&&<><h3>Opportunistic Piety</h3><p>{Math.max(0,n.piety-c.factotum.pietyUsed)} / {n.piety} daily uses remaining. Heal {2*n.level+n.intelligence} HP, damage undead, or turn undead as a level {n.level} cleric; resolve the target separately.</p><Btn disabled={n.remaining<1||c.factotum.pietyUsed>=n.piety} onClick={()=>edit(d=>{spendInspiration(d,1);d.factotum.pietyUsed++})}>Use Piety (1 inspiration)</Btn></>}
 {n.level>=2&&<><h3>Arcane Dilettante</h3><p className="fine">Choose after 8 hours of rest: each spell once, at most one level {n.maxSpellLevel} spell. Each use costs 1 inspiration. These are spell-like abilities, not wizard spell slots. Supply material components; spells with XP costs are excluded.</p>{c.factotum.spells.map(choice=>{const s=choice.spell,level=s.levels['Sorcerer / Wizard'];return <div className="subcard" key={s.id}><h4>{s.name} {choice.spent?'· used':''}</h4><p className="fine">Level {level} · CL {n.level} · DC {10+level+n.intelligence}</p><details><summary>Spell description</summary><p className="reference-text">{s.description}</p></details><Btn disabled={choice.spent||n.remaining<1||!!dilettanteProblem(c,s,c.factotum.spells.filter(x=>x!==choice).map(x=>x.spell))} onClick={()=>{if(roll({title:s.name+' — Arcane Dilettante',details:s.description,fields:[['Caster level',String(n.level)],['Save',`${s.save} (DC ${10+level+n.intelligence})`],['Duration',s.duration],['Range',s.range],['Components',s.components]]}))edit(d=>useDilettante(d,s.id))}}>Use spell and send card</Btn></div>})}{c.factotum.spells.length<n.spells&&<><F label="Find a daily spell" value={query} onChange={setQuery}/><div className="catalog-list">{eligible.slice(0,30).map(s=><div className="catalog-row" key={s.id}><span>{s.name} · {s.levels['Sorcerer / Wizard']}</span><Btn onClick={()=>edit(d=>chooseDilettante(d,s))}>Choose</Btn></div>)}</div><p className="fine">Showing up to 30 eligible spells. Narrow your search to find more.</p></>}</>}
 <Btn onClick={()=>confirm('Start a new Factotum day?','After the required rest, restore inspiration and daily abilities and clear Arcane Dilettante choices.',()=>edit(d=>{d.factotum={...d.factotum,spent:0,knowledgeUsed:[],pietyUsed:0,dodgeUsed:false,spells:[]}}))}>Reset Factotum day</Btn></Section>;
}
