'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {uid,type Feat} from '@/lib/model';
import {F,N,Choice,Btn,Section,type SheetProps} from './sheet-ui';
export function Features({c,edit,roll,confirm,feats}:{feats:Feat[]}&SheetProps){const [browse,setBrowse]=useState(false);const [query,setQuery]=useState('');return <Section title="Feats & features" action={<div className="button-row"><Btn onClick={()=>setBrowse(true)}>Browse SRD feats</Btn><Btn onClick={()=>edit(d=>{d.features.push({id:uid(),name:'New feature',kind:'Class feature',description:'',max:0,used:0,source:''})})}>+ Custom</Btn></div>}>
 {!c.features.length&&<p className="empty-note">Record feats, class features, racial traits, and daily abilities here.</p>}
 {c.features.map((f,i)=>{const set=(patch:Partial<typeof f>)=>edit(d=>{Object.assign(d.features[i],patch)});return <div className="subcard" key={f.id}><div className="fields two"><F label="Name" value={f.name} onChange={v=>set({name:v})}/><Choice label="Type" value={f.kind} onChange={v=>set({kind:v as typeof f.kind})} options={['Feat','Class feature','Racial trait','Other']}/></div><div className="fields two"><F label="Choice (weapon, skill or school)" value={f.choice||""} onChange={v=>set({choice:v})} placeholder="Battleaxe, Spot, Evocation…"/><F label="Daily limit formula (optional)" value={f.formula||""} onChange={v=>set({formula:v})} placeholder="3+CHA_MOD"/></div><F label="Description & notes" value={f.description} onChange={v=>set({description:v})} area/><div className="feature-controls"><N label="Daily uses (0 = untracked)" calculated={c.automation.enabled&&!!(f.ruleId||f.formula)} value={f.max} onChange={v=>set({max:v})} min={0}/><N label="Used today" value={f.used} onChange={v=>set({used:v})} min={0}/>{f.max>0&&<Btn disabled={f.used>=f.max} onClick={()=>set({used:f.used+1})}>Use ({Math.max(0,f.max-f.used)} left)</Btn>}<Btn onClick={()=>roll({title:f.name,details:f.description,fields:[['Type',f.kind]]})}>Post card</Btn><Btn className="quiet danger" onClick={()=>confirm('Remove '+f.name+'?','Remove this feat or feature from your sheet.',()=>edit(d=>{d.features=d.features.filter(x=>x.id!==f.id)}))}>Remove</Btn></div></div>})}
 <p className="fine">Common numeric feats apply automatically by name. For feats such as Weapon Focus, Skill Focus or Spell Focus, enter the matching weapon, skill or school in Choice. Class daily limits recalculate; custom feature limits accept formulas. Use a custom effect for other numerical rules.</p>
 <Dialog open={browse} onOpenChange={setBrowse}><DialogContent className="ledger-modal library-modal"><DialogHeader><DialogTitle>SRD feats</DialogTitle><DialogDescription>{feats.length} feats. Check prerequisites before selecting.</DialogDescription></DialogHeader><F label="Find a feat" value={query} onChange={setQuery} placeholder="Power Attack, Combat Casting…"/><div className="catalog-list">{feats.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())).map(f=><div className="catalog-row" key={f.id}><details><summary>{f.name}</summary><p className="reference-text">{f.description}</p></details><Btn onClick={()=>{edit(d=>{d.features.push({id:uid(),name:f.name,kind:'Feat',description:f.description,max:0,used:0,source:f.source})});setBrowse(false)}}>+ Add</Btn></div>)}{!feats.length&&<p className="empty-note">The feat library is loading. Close and reopen to retry after the reference data arrives.</p>}</div></DialogContent></Dialog>
 </Section>;}
