'use client';
import {assetUrl} from '@/lib/deployment';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {uid,abilityKeys,type Psionic} from '@/lib/model';
import {findClass,makePsionic} from '@/lib/classes';
import {formulaPreview} from '@/lib/automation';
import {psionicProgression} from '@/lib/advancement';
import {powerReserve,powerDC,canManifest,manifestingProblem,spendPower,powerCard,type PowerReference} from '@/lib/psionics';
import {withBonus} from '@/lib/rules';
import {F,N,Choice,Check,Btn,Section,Stat,type SheetProps} from './sheet-ui';
import {toast} from 'sonner';
import {effectiveScore,racialPowerPoints} from '@/lib/ancestry';
export function Powers({c,edit,roll,confirm}:SheetProps){const [active,setActive]=useState(''),[library,setLibrary]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[detail,setDetail]=useState<PowerReference|null>(null);const [refs,setRefs]=useState<PowerReference[]>([]),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);const [addOpen,setAddOpen]=useState(false),[kind,setKind]=useState('Psion');
 useEffect(()=>{let live=true;fetch(assetUrl('data/powers.json')).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<PowerReference[]>}).then(r=>{if(live){setRefs(r);setError('')}}).catch(()=>{if(live)setError('The power library could not be loaded.')});return()=>{live=false}},[attempt]);
 const p=c.psionics.find(x=>x.id===active)||c.psionics[0],reserve=powerReserve(c);const update=(patch:Partial<Psionic>)=>p&&edit(d=>Object.assign(d.psionics.find(x=>x.id===p.id)!,patch));
 const lists=Array.from(new Set(refs.flatMap(r=>Object.keys(r.levels)))).sort();const matches=refs.filter(r=>(r.name+' '+r.school).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||r.levels[filter]!==undefined));
 return <><Section title="Psionics" action={<Btn onClick={()=>setAddOpen(true)}>+ Psionic tradition</Btn>}>
 {!p?<div className="empty-note"><h3>No psionic tradition recorded</h3>{racialPowerPoints(c)>0&&<p>{reserve.remaining} of {reserve.max} racial power points remain. Record racial ability spending in Race.</p>}<p>Add a psion, psychic warrior, soulknife, or wilder to track power points, focus, and powers known.</p><Btn onClick={()=>setAddOpen(true)}>Add a tradition</Btn></div>:<>
 <Choice label="Manifesting tradition" value={p.id} options={c.psionics.map(x=>[x.id,x.name])} onChange={setActive}/><div className="stats"><Stat label="Shared daily reserve" value={reserve.max}/><Stat label="Points spent" value={reserve.spent}/><Stat label="Points remaining" value={reserve.remaining}/></div><p className="fine">Includes {racialPowerPoints(c)} racial power points. Psionic multiclass characters draw from one shared reserve. Each tradition contributes its daily points; the active tradition supplies its own manifester level and ability.</p><Check label="Psionically focused" checked={c.psionics.some(x=>x.focused)} onChange={v=>edit(d=>{d.psionics.forEach(x=>{x.focused=v})})}/>
 <details><summary>Manifesting settings</summary><div className="fields three"><F label="Tradition name" value={p.name} onChange={v=>update({name:v})}/><N label="Manifester level" calculated={c.automation.enabled&&!!p.manifesting?.automatic} value={p.level} min={0} max={100} onChange={v=>update({level:v})}/><Choice label="Manifesting ability" value={p.ability} options={[...abilityKeys]} onChange={v=>update({ability:v as Psionic['ability']})}/><N label="Daily PP contribution" calculated={c.automation.enabled&&!!p.manifesting?.automatic} value={p.max} min={0} max={10000} onChange={v=>update({max:v})}/><N label="Points spent using this tradition" value={p.spent} min={0} max={10000} onChange={v=>update({spent:v})}/><N label="Save DC adjustment" value={p.dcExtra} onChange={v=>update({dcExtra:v})}/></div><F label="Discipline, wild surge, overchannel & other notes" value={p.notes} onChange={v=>update({notes:v})} area/><Btn className="quiet danger" onClick={()=>confirm('Remove '+p.name+'?','Remove this tradition, its power-point contribution, and recorded powers.',()=>edit(d=>{d.psionics=d.psionics.filter(x=>x.id!==p.id)}))}>Remove tradition</Btn></details>
 <div className="button-row"><Btn onClick={()=>roll({title:p.name+' · manifester level check',formula:withBonus('1d20',p.level),details:'Use the current manifester level; enter temporary bonuses in settings.'})}>Manifester level check</Btn><Btn className="primary" onClick={()=>setLibrary(true)}>Browse {refs.length||''} powers</Btn><Btn onClick={()=>update({powers:[...p.powers,{id:uid(),powerId:'',name:'Custom power',level:1,cost:1,formula:'',notes:''}]})}>+ Custom power</Btn></div>
 {p.powers.length===0&&<p className="empty-note">Choose powers known from your class list and discipline. Your class reference gives the number known and maximum power level.</p>}
 {p.powers.map((k,i)=>{const r=refs.find(x=>x.id===k.powerId);const preview=formulaPreview(c,k.formula,{ML:p.level,PP:k.cost,SL:k.level});const set=(patch:Partial<typeof k>)=>edit(d=>Object.assign(d.psionics.find(x=>x.id===p.id)!.powers[i],patch));return <div className="subcard" key={k.id}><div className="row-head">{r?<button className="spell-title" onClick={()=>setDetail(r)}>{k.name}</button>:<F label="Power name" value={k.name} onChange={v=>set({name:v})}/>}<span className="spell-dc">{r?.save.toLowerCase()==='none'?'No save':'Base DC '+powerDC(c,p,k)}</span></div><div className="fields three"><N label="Power level" value={k.level} min={1} max={9} onChange={v=>set({level:v})}/><N label="PP cost including augmentation" value={k.cost} min={1} max={100} onChange={v=>set({cost:v})}/><F label="Effect roll (optional)" value={k.formula} onChange={v=>set({formula:v})} placeholder="3d6+3"/></div><div className="button-row"><Btn className="primary" disabled={!canManifest(c,p,k)} onClick={()=>{if(roll(powerCard(c,p,k,r)))edit(d=>spendPower(d,p.id,k.id))}}>Manifest · {k.cost} PP</Btn><Btn onClick={()=>roll(powerCard(c,p,k,r))}>Post card</Btn>{preview.formula&&<Btn onClick={()=>roll({title:k.name+' · effect',formula:preview.formula,details:k.notes})}>Roll effect</Btn>}<Btn className="quiet danger" onClick={()=>confirm('Remove '+k.name+'?','Remove this power from powers known.',()=>update({powers:p.powers.filter(x=>x.id!==k.id)}))}>Remove</Btn></div>{preview.error&&<p className="error-text">{preview.error}</p>}{!canManifest(c,p,k)&&<p className="fine">{manifestingProblem(c,p,k)}</p>}<F label="Augmentation, effects, and notes" value={k.notes} onChange={v=>set({notes:v})} area/></div>})}
 <p className="fine">Manifest spends points and posts a card. Choose augmented cost; scalable effect formulas accept {'{PP}d6'}, {'{ML}'}, {'{SL}'}, and ability modifiers. Check power-specific DC increases, wild surge, focus expenditure, and other exceptions in the description. Reset daily uses restores power points.</p>
 </>}
 </Section>
 <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="ledger-modal"><DialogHeader><DialogTitle>Add a psionic tradition</DialogTitle><DialogDescription>Start with level 3 example values; adjust manifester level and daily points for your character.</DialogDescription></DialogHeader><Choice label="Class" value={kind} onChange={setKind} options={['Psion','Psychic Warrior','Soulknife','Wilder']}/><Btn className="primary" onClick={()=>{const def=findClass(kind)!;const ability=kind==='Psion'?'INT':kind==='Wilder'?'CHA':'WIS';const profile=makePsionic(def,3,effectiveScore(c,ability));edit(d=>{d.psionics.push(profile)});setActive(profile.id);setAddOpen(false)}}>Add tradition</Btn></DialogContent></Dialog>
 <Dialog open={library} onOpenChange={setLibrary}><DialogContent className="ledger-modal library-modal"><DialogHeader><DialogTitle>Psionic power library</DialogTitle><DialogDescription>{refs.length} SRD powers. Check your class list, discipline, and powers-known limit.</DialogDescription></DialogHeader><div className="fields two"><F label="Search powers" value={query} onChange={setQuery}/><Choice label="Class / discipline" value={filter} onChange={setFilter} options={[[ 'all','All lists'],...lists]}/></div><div className="catalog-list">{error?<div className="error-box">{error}<Btn onClick={()=>setAttempt(n=>n+1)}>Retry</Btn></div>:matches.map(r=><div className="catalog-row" key={r.id}><div><button className="spell-title" onClick={()=>setDetail(r)}>{r.name}</button><p className="fine">{r.levelText} · {r.cost} PP</p></div><Btn disabled={!p} onClick={()=>{if(!p)return;const level=r.levels[filter]??r.levels[p.name==='Psychic Warrior'?'Psychic Warrior':'Psion/Wilder']??Math.min(...Object.values(r.levels));update({powers:[...p.powers,{id:uid(),powerId:r.id,name:r.name,level,cost:Math.max(1,r.cost),formula:'',notes:''}]});toast.success(r.name+' added.')}}>+ Add</Btn></div>)}{!error&&!matches.length&&<p className="empty-note">{refs.length?'No powers match.':'Loading powers…'}</p>}</div></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="ledger-modal reference-modal"><DialogHeader><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.school} · {detail?.levelText}</DialogDescription></DialogHeader>{detail&&<><dl className="spell-metadata">{[['Power points',String(detail.cost)],['Display',detail.display],['Manifesting time',detail.manifesting],['Range',detail.range],['Target / area',detail.target],['Duration',detail.duration],['Saving throw',detail.save],['Power resistance',detail.resistance]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="reference-text">{detail.description}</p><a className="source-link" href={detail.source} target="_blank" rel="noreferrer">Read SRD power reference</a></>}</DialogContent></Dialog>
 </>;
}
