'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {findRace,effectiveScore} from '@/lib/ancestry';
import {hasFeat} from '@/lib/effects';
import {applyRacialFireDamage,sigils,sigilLimit,illumianWord,setSigils,useIllumianWord,reserveIllumianSlot,swimSpeed,racialWarnings,racialHD,metamagicCosts,advanceRacialRound,racialEnabled} from '@/lib/racial-abilities';
import {skillBonus,withBonus,makeSpellRoll} from '@/lib/rules';
import {Choice,Check,N,Btn,Section,type SheetProps} from './sheet-ui';
const elements=['none','air','earth','fire','water','cold'];
const summaries:Record<string,string>={Aeshkrau:'Choose which traditions use Strength for bonus spells.',Uurkrau:'Choose which traditions use Dexterity for bonus spells.',Aeshoon:'Swift: spend a turning/rebuking use; focused weapons gain Wisdom-bonus damage until your next turn.',Aeshuur:'After a sneak attack or critical hit, activate and select the affected opponent. Dodge applies only against that opponent.',Hoonkrau:'Swift: turning enhances cure rolls; rebuking enhances inflict rolls. Lasts through the end of your next turn.',Hoonvaul:'Swift: sacrifice an unprepared slot for turning and smite bonuses until your next turn.',Naenaesh:'During preparation, reserve up to two slots for Still Spell access.',Naenhoon:'Swift: pay turning/rebuking attempts for a known metamagic feat. Resolve its effect on the selected spell.',Naenkrau:'During preparation, reserve up to two slots at different levels for higher save DCs.',Uurhoon:'Swift: sacrifice an unprepared slot for Reflex and spell-resistance checks.',Uurnaen:'During preparation, reserve one level 1 or 2 slot for unarmed/sneak attack accuracy.',Vaulaesh:'Swift: sacrifice an unprepared slot for AC and focused-weapon damage.',Vaulkrau:'Immediate: sacrifice an unprepared slot for your next saving throw before your next turn.',Vaulnaen:'Cast a prepared spell using a matching unprepared donor slot. The original preparation remains.',Vauluur:'Swift: sacrifice an unprepared slot for extra unarmed/sneak damage until your next turn.'};
export function RacialAbilities({c,edit,roll,spells}:{spells?:import('@/lib/model').Spell[]}&SheetProps){
 const [fireDamage,setFireDamage]=useState(0),[otherResistance,setOtherResistance]=useState(0);const [casterId,setCaster]=useState(''),[level,setLevel]=useState(1),[turnId,setTurn]=useState(''),[mode,setMode]=useState('turn'),[meta,setMeta]=useState(''),[targetId,setTarget]=useState(''),[spellId,setSpell]=useState('');
 const race=findRace(c.ancestry.raceId),word=illumianWord(c),env=c.racialState.environment,swim=swimSpeed(c),enabled=racialEnabled(c);
 if(!race)return null;
 const sensitive=['kobold','earth-kobold','aquatic-kobold','orc','water-orc','duergar','deep-dwarf'].includes(race.id);
 const environmentRelevant=swim>0||race.waterBreathing||race.element||race.type.includes('dwarf')||race.id==='illumian'||sensitive||racialWarnings(c).length>0;
 const attempt=(f:()=>void)=>{try{f()}catch(e){toast.error(e instanceof Error?e.message:'Check the racial ability.')}};
 const setEnv=(patch:Partial<typeof env>)=>edit(d=>{Object.assign(d.racialState.environment,patch)});
 const donor=c.casters.find(p=>p.id===casterId)||c.casters[0],turns=c.features.filter(f=>/^(?:turn(?: or rebuke)?|rebuke|command) undead/i.test(f.name)),turn=turns.find(f=>f.id===turnId)||turns[0];
 const target=c.casters.find(p=>p.id===targetId)||c.casters[0],prepared=target?.spells.find(k=>k.id===spellId)||target?.spells[0];
 const metas=Object.keys(metamagicCosts).filter(m=>hasFeat(c,m)),chosenMeta=metas.includes(meta)?meta:metas[0]||'';
 const activate=()=>attempt(()=>{const options={casterId:donor?.id,level,turnId:turn?.id,mode,metamagic:chosenMeta,targetCasterId:target?.id,targetSpellId:prepared?.id};const draft=structuredClone(c);useIllumianWord(draft,options);if(word==='Vaulnaen'){const reference=prepared?.custom||spells?.find(s=>s.id===prepared?.spellId);if(!target||!prepared||!reference)throw new Error('Open the spell library to load this spell reference, or use a custom spell.');if(!roll({...makeSpellRoll(c,target,prepared,reference),details:'Vaulnaen: donor slot spent; original preparation retained.'}))return;}edit(d=>useIllumianWord(d,options));});
 return <>
 {race.id==='illumian'&&<Section title="Illumian sigils & words">
 {!enabled&&<p className="fine">Enable automatic calculations and racial trait bonuses to apply these powers.</p>}
 <p className="fine">Choose one sigil at first level; a second unlocks when any class reaches level 2. This grants no human bonus feat or skill points.</p>
 <div className="fields two"><Choice label="First sigil" value={c.racialState.sigils[0]||'none'} options={['none',...sigils]} onChange={v=>attempt(()=>edit(d=>setSigils(d,[v,...d.racialState.sigils.slice(1)].filter(x=>x!=='none'))))}/>{sigilLimit(c)===2&&<Choice label="Second sigil" value={c.racialState.sigils[1]||'none'} options={['none',...sigils.filter(s=>s!==c.racialState.sigils[0])]} onChange={v=>attempt(()=>edit(d=>setSigils(d,[...d.racialState.sigils.slice(0,1),v].filter(x=>x!=='none'))))}/>}</div>
 <p className="fine">Aesh: Strength checks. Hoon: Constitution/Wisdom checks. Naen: Intelligence checks. Uur: Dexterity checks and initiative. Vaul: Charisma checks. These include associated skills, not scores or ordinary attacks/saves. Krau increases spell and spell-like caster level up to Hit Dice.</p>
 <Check label="Suppress luminous sigils (standard action); restore as a free action" checked={c.racialState.suppressed} onChange={v=>edit(d=>{d.racialState.suppressed=v})}/>
 <h3>{word||'No active power word'}</h3>{word&&<p>{summaries[word]}</p>}
 {['Aeshkrau','Uurkrau'].includes(word)&&c.casters.map(p=><Check key={p.id} label={p.name+': use '+(word==='Aeshkrau'?'Strength':'Dexterity')+' for bonus slots only'} checked={c.racialState.bonusCasters.includes(p.id)} onChange={v=>edit(d=>{d.racialState.bonusCasters=v?[...new Set([...d.racialState.bonusCasters,p.id])]:d.racialState.bonusCasters.filter(id=>id!==p.id)})}/>)}
 {word&&!['Aeshkrau','Uurkrau','Aeshuur'].includes(word)&&<div className="fields two">{donor&&<Choice label="Slot / reservation tradition" value={donor.id} options={c.casters.map(p=>[p.id,p.name])} onChange={setCaster}/>}<N label={word==='Naenhoon'?'Slot level / Heighten increase':'Slot level'} value={level} min={0} max={9} onChange={setLevel}/>{turn&&['Aeshoon','Hoonkrau','Naenhoon'].includes(word)&&<Choice label="Turning or rebuking pool" value={turn.id} options={turns.map(f=>[f.id,f.name+' · '+Math.max(0,f.max-f.used)+' left'])} onChange={setTurn}/>}</div>}
 {word==='Hoonkrau'&&<Choice label="Attempt type" value={mode} options={[["turn","Turn: enhance cure"],["rebuke","Rebuke: enhance inflict"]]} onChange={setMode}/>}
 {['Naenhoon','Vaulnaen'].includes(word)&&<div className="fields two">{target&&<Choice label="Spell tradition" value={target.id} options={c.casters.map(p=>[p.id,p.name])} onChange={setTarget}/>} {prepared&&<Choice label="Spell" value={prepared.id} options={(target?.spells||[]).map(k=>[k.id,k.custom?.name||spells?.find(s=>s.id===k.spellId)?.name||k.spellId])} onChange={setSpell}/>} {word==='Naenhoon'&&chosenMeta&&<Choice label="Known metamagic feat" value={chosenMeta} options={metas} onChange={setMeta}/>}</div>}
 {['Naenaesh','Naenkrau','Uurnaen'].includes(word)?<Btn disabled={!donor} onClick={()=>attempt(()=>edit(d=>reserveIllumianSlot(d,donor?.id||'',level)))}>Leave this slot unfilled</Btn>:word&&!['Aeshkrau','Uurkrau'].includes(word)&&<Btn disabled={!enabled} onClick={activate}>{word==='Vaulnaen'?'Cast using donor slot':word==='Aeshuur'?'Activate after qualifying hit':'Activate word'}{word!=='Aeshuur'?' · '+Math.max(0,2-(c.racialState.uses[word]||0))+' uses left':''}</Btn>}
 {c.racialState.reservations.length>0&&<p className="fine">Reserved until the next daily reset/preparation: {c.racialState.reservations.map(r=>(c.casters.find(p=>p.id===r.casterId)?.name||'Missing tradition')+' level '+r.level+' ('+r.word+')').join('; ')}. These slots are removed from daily capacity; suppressing sigils does not refund them.</p>}
 {word==='Aeshuur'&&<Check label="Current incoming attack is from the opponent that triggered Aeshuur" checked={env.wordTarget} onChange={v=>setEnv({wordTarget:v})}/>}
 {c.racialState.active&&<><p className="fine">{c.racialState.active.word}: {c.racialState.active.rounds} round(s) remaining. {c.racialState.active.mode}</p><div className="button-row"><Btn onClick={()=>edit(d=>advanceRacialRound(d))}>Advance racial effect one round</Btn><Btn onClick={()=>edit(d=>{d.racialState.active=null})}>End racial effect</Btn></div></>}
 <p className="fine">Tick effects when the named turn boundary occurs; Hoonkrau lasts through your next turn, Uurhoon uses minutes, and Vaulkrau ends after the next save. The general Advance one round button also advances racial timers. Naenhoon records the paid metamagic; apply its spell effect using the spell’s existing controls.</p>
 <a className="source-link" href={race.source} target="_blank" rel="noreferrer">Illumian source rules</a>
 </Section>}
 {environmentRelevant&&<Section title="Racial environment & defenses">
 {racialWarnings(c).map(s=><p key={s} className="fine">{s}</p>)}
 {swim>0&&<><p>Swim speed: <strong>{swim} ft.</strong> · +8 racial Swim bonus · take 10 while threatened · run in a straight line.</p><Btn onClick={()=>{const s=c.skills.find(s=>s.name==='Swim');if(s)roll({title:'Swim',formula:withBonus('1d20',skillBonus(c,s)),details:'Racial swim speed '+swim+' ft. Ordinary swimming at this speed needs no check.'})}}>Roll Swim</Btn><Btn onClick={()=>{const s=c.skills.find(s=>s.name==='Swim');if(s)roll({title:'Swim · take 10',fields:[['Result',String(10+skillBonus(c,s))]],details:'May take 10 despite distraction or danger.'})}}>Take 10</Btn></>}
 {race.waterBreathing&&<><Check label="Currently underwater" checked={env.underwater} onChange={v=>setEnv({underwater:v})}/><N label="Rounds spent holding breath outside water" value={env.breathRounds} min={0} max={10000} onChange={v=>setEnv({breathRounds:v})}/><p className="fine">{Math.max(0,2*effectiveScore(c,'CON')-env.breathRounds)} breath rounds remain. After the limit, make escalating Constitution checks (starting DC 10) and apply suffocation rules; ordinary air breathing is not granted.</p></>}
 {race.element?.startsWith('air')&&<p className="fine">Breathless: no drowning, suffocation, or inhalation exposure.</p>}{race.element==='fire'&&<><p className="fine">Fire resistance 5. Enter one fire-damage event after its save and other adjustments; the higher resistance applies, followed by temporary HP.</p><div className="fields two"><N label="Fire damage before resistance" value={fireDamage} min={0} max={10000} onChange={setFireDamage}/><N label="Other fire resistance" value={otherResistance} min={0} max={10000} onChange={setOtherResistance}/></div><Btn disabled={!enabled||fireDamage===0} onClick={()=>attempt(()=>{edit(d=>applyRacialFireDamage(d,fireDamage,otherResistance));setFireDamage(0)})}>Apply fire damage to HP</Btn></>}
 {race.element&&<div className="fields two"><Choice label="Opponent subtype" value={env.targetElement} options={elements} onChange={v=>setEnv({targetElement:v as typeof env.targetElement})}/><Choice label="Incoming magical effect element" value={env.magicElement} options={elements} onChange={v=>setEnv({magicElement:v as typeof env.magicElement})}/><Choice label="Incoming magical ability: source creature subtype" value={env.magicSource} options={elements} onChange={v=>setEnv({magicSource:v as typeof env.magicSource})}/>{race.id==='air-gnome'&&<Check label="Opponent is Large or larger" checked={env.targetLarge} onChange={v=>setEnv({targetLarge:v})}/>}</div>}
 {(race.element==='earth'||race.type.includes('dwarf'))&&<><Check label="Standing firmly on the ground" checked={env.grounded} onChange={v=>setEnv({grounded:v})}/><Check label="Ability check resists a bull rush or trip" checked={env.resistTrip} onChange={v=>setEnv({resistTrip:v})}/></>}
 {race.element==='earth'&&<Check label="Relevant stonework / stone or metal crafting task" checked={env.stonework} onChange={v=>setEnv({stonework:v})}/>}
 {sensitive&&<Check label="Bright sunlight or daylight" checked={env.brightLight} onChange={v=>setEnv({brightLight:v})}/>}
 {race.id==='illumian'&&<><Check label="Incoming spell has the shadow descriptor" checked={env.shadow} onChange={v=>setEnv({shadow:v})}/><Check label="Incoming magic is glyph, rune, sigil, or symbol based" checked={env.glyph} onChange={v=>setEnv({glyph:v})}/>{env.glyph&&<N label={'Incoming caster level (racial HD '+racialHD(c)+')'} value={env.incomingCasterLevel} min={0} max={100} onChange={v=>setEnv({incomingCasterLevel:v})}/>}</>}
 <p className="fine">Set these for the current roll, then clear them when the situation changes. Bonuses follow the racial automation switch. Environmental variants retain their original creature type; elemental affinity alone does not give the elemental type or subtype.</p>
 </Section>}</>;
}
