'use client';
import {useState} from 'react';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {F,N,Choice,Check,Btn,Section,Stat,type SheetProps} from './sheet-ui';
import {abilityKeys,uid,type Skill} from '@/lib/model';
import {canRollSkill,skillBonus,signed,withBonus} from '@/lib/rules';
import {racialSkill} from '@/lib/ancestry';
import {advancementNumbers} from '@/lib/advancement';
import {skillLedger,nextSkillPurchase,spendNextSkillPoint,classSkillAt,availableSkillPoints,setSkillPoints,assignExistingSkillRanks,moveSkillLevel,removeSkillPurchases} from '@/lib/skill-points';

export function SkillsView({c,edit,roll,confirm}:SheetProps){
  const [search,setSearch]=useState(''),[trainedOnly,setTrainedOnly]=useState(false),[classOnly,setClassOnly]=useState(false),[selected,setSelected]=useState('');
  const ledger=skillLedger(c),row=ledger.levels.find(r=>r.key===selected)||ledger.levels.find(r=>r.remaining>0)||ledger.levels.at(-1);
  const automatic=c.automation.enabled&&c.automation.skillTraining.version===1,totals=advancementNumbers(c);
  const history=row?c.automation.history.find(h=>h.key===row.key):undefined;
  const skills=c.skills.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())&&(!trainedOnly||s.ranks>0)&&(!classOnly||!row||classSkillAt(c,s,row)));
  function points(id:string,value:number){if(!row)return;edit(d=>{const skill=d.skills.find(s=>s.id===id),h=d.automation.history.find(h=>h.key===row.key);if(!skill||!h)return;const old=(h.skillRanks[id]||0)*(classSkillAt(d,skill,row)?1:2);setSkillPoints(d,row.key,id,Math.max(0,Math.min(Math.floor(value),old+availableSkillPoints(d,row.key,id))))})}
  return <>
    <Section title="Skill training" note="Choose the level where you bought a skill. Points, ranks, and check bonuses update together.">
      <div className="stats skill-budget"><Stat label="Points earned" value={ledger.granted}/><Stat label="Points spent" value={automatic?ledger.spent:totals.skillSpent}/><Stat label="Still to allocate" value={automatic?ledger.remaining:totals.skillRemaining}/></div>
      {!automatic&&<p className="fine">Enable automatic calculations under Calculations to buy ranks by level. Manual rank entry is currently active.</p>}
      {row&&<div className="training-toolbar"><Choice label="Spend points at" value={row.key} onChange={setSelected} options={ledger.levels.map(r=>[r.key,'Level '+(r.index+1)+' · '+r.label+' · '+r.remaining+' points left'])}/><div className="training-balance"><strong>{row.remaining}</strong><span>of {row.granted} points left at this level</span></div></div>}
      <p className="fine">One point buys 1 class-skill rank or ½ cross-class rank. A class skill from an earlier class keeps the higher rank limit, but its purchase cost follows the class you are advancing. Points belong to the level that granted them. When the selected level is full or capped, + continues at the next eligible level. The points field and refund button apply only to the selected level.</p>
      {automatic&&ledger.warnings.slice(0,12).map(w=><p className="error-box" key={w}>{w}</p>)}
      {automatic&&ledger.unassigned>0&&<details className="training-import" open><summary>Assign existing ranks</summary><p className="fine">Your earlier ranks are preserved. Fit them to available levels automatically, then review the allocation. Any ranks that do not fit remain listed here.</p><Btn onClick={()=>edit(assignExistingSkillRanks)}>Fit existing ranks to levels</Btn><div className="fields three">{c.skills.filter(s=>(c.automation.skillTraining.unassigned[s.id]||0)>0).map(s=><N key={s.id} label={s.name+' unassigned ranks'} value={c.automation.skillTraining.unassigned[s.id]} min={0} max={1000} step={.5} onChange={v=>edit(d=>{d.automation.skillTraining.unassigned[s.id]=Math.round(v*2)/2})}/>)}</div></details>}
      <details className="training-history"><summary>Level order, Intelligence, and point grants</summary><p className="fine">Intelligence is recorded at each level. Later increases do not grant points retroactively; enhancement bonuses such as a headband do not add skill points. Put multiclass levels in the order you took them; new levels append to that history. Reordering can change your first Hit Die and first-level skill grant.</p>
        {ledger.levels.map((r,index)=>{const h=c.automation.history.find(h=>h.key===r.key);return <div className="subcard training-level" key={r.key}><div className="row-head"><h3>{index+1}. {r.label}</h3><span>{r.spent} / {r.granted} points</span></div><div className="fields three"><N label="Intelligence at this level" value={h?.intScore??10} min={1} max={100} onChange={v=>edit(d=>{const h=d.automation.history.find(h=>h.key===r.key);if(h)h.intScore=Math.floor(v)})}/><N label="Points granted" value={h?.skillPoints??r.granted} min={0} max={1000} onChange={v=>edit(d=>{const h=d.automation.history.find(h=>h.key===r.key);if(h)h.skillPoints=Math.floor(v)})}/><div className="button-row training-order"><Btn disabled={!index||r.classId==='racial'||ledger.levels[index-1].classId==='racial'||ledger.levels[index-1].entryId===r.entryId} onClick={()=>edit(d=>moveSkillLevel(d,r.key,-1))}>Earlier</Btn><Btn disabled={index===ledger.levels.length-1||r.classId==='racial'||ledger.levels[index+1]?.entryId===r.entryId} onClick={()=>edit(d=>moveSkillLevel(d,r.key,1))}>Later</Btn>{h?.skillPoints!==undefined&&<Btn onClick={()=>edit(d=>{delete d.automation.history.find(h=>h.key===r.key)!.skillPoints})}>Use class grant</Btn>}</div></div></div>})}
      </details>
    </Section>
    <Section title="Skills" note="Checks include abilities, racial traits, armor, feats, synergy, and active effects." action={<Btn disabled={c.skills.length>=120} onClick={()=>edit(d=>{d.skills.push({id:uid(),name:'Craft (specialty)',ability:'INT',ranks:0,misc:0,trained:false,armor:0,classSkill:false})})}>+ Specialty</Btn>}>
      <div className="skill-filters"><F label="Find a skill" value={search} onChange={setSearch} placeholder="Listen, Knowledge, Craft…"/><Check label="With ranks only" checked={trainedOnly} onChange={setTrainedOnly}/>{automatic&&<Check label="Class skills at this level" checked={classOnly} onChange={setClassOnly}/>}</div>
      <Table className="skills-table training-table"><TableHeader><TableRow><TableHead>Skill / ability</TableHead>{automatic&&<><TableHead>Training</TableHead><TableHead>This level</TableHead></>}<TableHead>Total ranks</TableHead><TableHead>Misc.</TableHead><TableHead>Check</TableHead></TableRow></TableHeader><TableBody>
        {skills.map(s=>{const update=(patch:Partial<Skill>)=>edit(d=>{Object.assign(d.skills.find(x=>x.id===s.id)!,patch)}),custom=!s.id.startsWith('skill-'),isClass=row?classSkillAt(c,s,row):s.classSkill,cost=isClass?1:2,current=(history?.skillRanks[s.id]||0)*cost,available=row?.available[s.id]||0,language=s.name==='Speak Language',next=row?nextSkillPurchase(ledger.levels,row.key,s.id):undefined;return <TableRow key={s.id}>
          <TableCell><div className="skill-name">{custom?<F label="Specialty name" value={s.name} onChange={v=>update({name:v})}/>:<strong>{s.name}</strong>}<span className="fine">{language?'Record learned languages in Notes':s.ability+(s.trained?' · trained':'')+(s.armor?' · armor ×'+s.armor:'')}</span>{custom&&<details><summary>Skill settings</summary><Choice label="Ability" value={s.ability} options={[...abilityKeys]} onChange={v=>update({ability:v as Skill['ability']})}/><N label="Armor penalty multiplier" value={s.armor} min={0} max={2} onChange={v=>update({armor:v})}/><Check label="Trained only" checked={s.trained} onChange={v=>update({trained:v})}/><Btn className="quiet danger" onClick={()=>confirm('Remove skill?','Remove this specialty and refund its recorded skill points.',()=>edit(d=>{removeSkillPurchases(d,s.id);d.skills=d.skills.filter(x=>x.id!==s.id)}))}>Remove</Btn></details>}</div></TableCell>
          {automatic&&<><TableCell><details className="training-cost"><summary>{isClass?'Class':'Cross-class'}</summary><span className="fine">{cost} point{cost===1?'':'s'} / rank</span>{row&&<Choice label={s.name+' training at this level'} value={history?.skillClassOverrides[s.id]===undefined?'auto':history.skillClassOverrides[s.id]?'class':'cross'} options={[[ 'auto','Follow class'],['class','Class (house rule)'],['cross','Cross-class (house rule)']]} onChange={v=>edit(d=>{const h=d.automation.history.find(h=>h.key===row.key);if(h){if(v==='auto')delete h.skillClassOverrides[s.id];else h.skillClassOverrides[s.id]=v==='class'}})}/>}</details></TableCell><TableCell><div className="point-purchase"><Btn aria-label={'Refund one point from '+s.name} disabled={!row||current<=0} onClick={()=>points(s.id,current-1)}>−</Btn><N label={s.name+' points at this level'} value={current} min={0} max={current+available} onChange={v=>points(s.id,v)}/><Btn aria-label={'Spend one point on '+s.name} disabled={!next} title={next?'Spend at level '+(next.index+1):'No points or rank capacity at this or a later level'} onClick={()=>{if(row&&next){edit(d=>{spendNextSkillPoint(d,row.key,s.id)});setSelected(next.key)}}}>+</Btn></div>{next&&next.key!==row?.key&&<span className="fine">Next point: level {next.index+1} · {next.costs[s.id]===1?'1 rank':'½ rank'}</span>}</TableCell></>}
          <TableCell><N calculated={automatic} label={s.name+' ranks'} value={s.ranks} onChange={v=>update({ranks:Math.round(v*2)/2})} min={0} max={1000} step={.5}/>{automatic&&row&&<span className="fine">limit {ledger.levels.at(-1)?.limits[s.id]}</span>}</TableCell><TableCell><N label={s.name+' misc.'} value={s.misc} onChange={v=>update({misc:v})}/></TableCell><TableCell>{language?<span className="fine">No check</span>:<Btn disabled={!canRollSkill(s)} title={!canRollSkill(s)?'Requires at least 1 rank':'Roll '+s.name} onClick={()=>roll({title:s.name+' check',formula:withBonus('1d20',skillBonus(c,s)),details:`Ranks ${s.ranks}; ${s.ability}; armor ${s.armor*c.defense.checkPenalty}; misc ${signed(s.misc)}; race/size ${signed(racialSkill(c,s))}.`})}>{signed(skillBonus(c,s))}</Btn>}</TableCell>
        </TableRow>})}
      </TableBody></Table>
      {!skills.length&&<p className="empty-note">No skills match this search.</p>}<p className="fine">Only whole ranks improve checks. Refunding a point reduces its ranks immediately. Training-type and point-grant overrides are available for house rules.</p>
    </Section>
  </>;
}
