import {classCatalog} from './class-catalog.ts';
import {monkStyleBonus} from './alternate-grants.ts';
import {featureReplaced,hasAlternateFeature,alternateSettings} from './alternate-features.ts';
import {krauBonus,racialBonusAbility,reservedSlots} from './racial-abilities.ts';
import type {Character,Caster,Psionic} from './model.ts';
import {findClass,spellSlots,castingLevel,manifestingLevel,classTotals} from './classes.ts';
import {effectiveScore,racialBonusFeat} from './ancestry.ts';
import {classLevel,featCount,hasFeat} from './effects.ts';
import {hitDieSequence,skillPointGrant} from './level-history.ts';
import {skillLedger} from './skill-points.ts';
export {hitDieSequence} from './level-history.ts';
import known from './spells-known.json' with {type:'json'};
export const arcaneClasses=['wizard','sorcerer','bard','assassin',...classCatalog.filter(d=>d.casting?.type==='arcane').map(d=>d.id)];
export function castingDefinition(p:Caster){return findClass(p.casting?.classId||p.name)||findClass(p.list);}
export function manifestDefinition(p:Psionic){return findClass(p.manifesting?.classId||p.name);}
export function advanceTargets(c:Character,e:Character['classLevels'][number]){const definition=findClass(e.classId);const texts=definition?.levels.filter(r=>r.level<=e.level).map(r=>[r.special,...r.extra].join(' '))||[];const text=texts.join(' ');const dual=e.classId==='mystic-theurge',psi=/manifesting/.test(text);return {spell:e.classId==='master-specialist'||/existing.*(?:spellcasting|arcane)|existing class/.test(text),divine:dual||e.classId==='hierophant',psi,arcane:/arcane/.test(text),spellLevels:e.classId==='master-specialist'?Math.min(e.level,10):texts.filter(t=>/\+1\s*level of existing/.test(t)&&!(/^.*manifesting.*$/.test(t)&&!t.includes('spellcasting'))).length,psiLevels:texts.filter(t=>/\+1\s*level of existing manifesting/.test(t)).length};}
export function advancementCandidates(c:Character,e:Character['classLevels'][number],kind:'spell'|'divine'|'psi'){
 const target=advanceTargets(c,e);
 if(kind==='psi')return c.psionics.filter(p=>manifestDefinition(p)?.id!=='soulknife').map(p=>({id:p.id,name:p.name}));
 return c.casters.filter(p=>!p.casting?.domain&&(e.classId!=='master-specialist'||castingDefinition(p)?.id==='wizard')&&(kind==='divine'?!arcaneClasses.includes(castingDefinition(p)?.id||''):!target.arcane||arcaneClasses.includes(castingDefinition(p)?.id||''))).map(p=>({id:p.id,name:p.name}));
}
function selected(c:Character,e:Character['classLevels'][number],kind:'spell'|'divine'|'psi'){
 const explicit=kind==='psi'?e.psionicTarget:kind==='divine'?e.divineTarget:e.castingTarget;
 const candidates=advancementCandidates(c,e,kind);
 if(explicit)return explicit!=='none'&&candidates.some(p=>p.id===explicit)?explicit:'';
 return candidates.length===1?candidates[0].id:'';
}
export function casterProgression(c:Character,p:Caster):{progression:number;level:number;linked:boolean}{const d=castingDefinition(p);if(!d)return {progression:0,level:p.level,linked:false};if(featureReplaced(c,d.id,'spellcasting'))return {progression:0,level:0,linked:true};const base=classLevel(c,d.id);let addition=0,clOnly=0;for(const e of c.classLevels){const t=advanceTargets(c,e);if(t.spell&&selected(c,e,'spell')===p.id)addition+=t.spellLevels;if(t.divine&&selected(c,e,'divine')===p.id){if(e.classId==='hierophant')clOnly+=e.level;else addition+=t.spellLevels;}}
 // Domain profiles follow the selected cleric tradition, including prestige advancement.
 if(p.casting?.domain){const primary=c.casters.find(q=>q.id!==p.id&&!q.casting?.domain&&castingDefinition(q)?.id===d.id);if(primary){const r=casterProgression(c,primary);return {...r,level:r.level+(p.casting.levelAdjustment||0)}}}
 const progression=p.casting?.progression??(base+addition);const level=(d.id==='spellthief'&&hasAlternateFeature(c,'spellthief-trickster')?progression:castingLevel(d,progression))+clOnly+(p.casting?.levelAdjustment||0);return {progression,level:level+krauBonus(c,level),linked:base>0||p.casting?.progression!=null};}
export function psionicProgression(c:Character,p:Psionic){const d=manifestDefinition(p);if(!d)return {progression:0,level:p.level,linked:false};const base=classLevel(c,d.id);let extra=0;for(const e of c.classLevels){const t=advanceTargets(c,e);if(t.psi&&selected(c,e,'psi')===p.id)extra+=t.psiLevels;}const progression=p.manifesting?.progression??base+extra;return {progression,level:d.id==='soulknife'?0:Math.max(0,manifestingLevel(d,progression)+(p.manifesting?.levelAdjustment||0)),linked:base>0||p.manifesting?.progression!=null};}
export function castingNumbers(c:Character,p:Caster){const d=castingDefinition(p),r=casterProgression(c,p);const siberys=d?.id==='sorcerer'&&hasAlternateFeature(c,'sorcerer-blood-of-siberys')?4:0;const score=effectiveScore(c,p.ability,true)+siberys;const table=d?.id==='spellthief'&&hasAlternateFeature(c,'spellthief-trickster')?findClass('bard'):d;const row=table?.levels.find(v=>v.level===Math.min(r.progression,table.levels.length));let slots:number[]=row?.slots?spellSlots(table!,row.level,score,effectiveScore(c,racialBonusAbility(c,p,d?.casting?.bonusAbility||p.ability),true)+siberys).map(s=>s.max):Array(10).fill(0);if(p.casting?.domain)slots=slots.map((_,i)=>i>0&&row?.slots?.[i]!=null&&score>=10+i?1:0);if(d&&featureReplaced(c,d.id,'spellcasting'))slots=Array(10).fill(0);slots=slots.map((v,i)=>Math.max(0,Math.floor(v+(p.casting?.slotAdjustments[i]||0)-reservedSlots(c,p,i))));if(d&&featureReplaced(c,d.id,'spellcasting'))slots=Array(10).fill(0);if(d?.id==='cleric'&&!p.casting?.domain&&hasAlternateFeature(c,'cleric-pool-of-healing'))slots[4]=Math.max(0,slots[4]-1);if(d?.id==='cleric'&&p.casting?.domain&&featureReplaced(c,'cleric','domains'))slots=Array(10).fill(0);if(d?.id==='cleric'&&!p.casting?.domain&&hasAlternateFeature(c,'cleric-no-turning')&&alternateSettings(c,'cleric-no-turning').choice==='Mystic'&&!featureReplaced(c,'cleric','spellcasting')){const highest=row?.slots?.findLastIndex((v,i)=>v!==null&&v!==undefined&&score>=10+i)??0;if(highest>0)slots[highest-1]++;}const knownTables=known as Record<string,Record<string,number[]>>;let allowance=table?knownTables[table.id]?.[String(Math.min(r.progression,table.levels.length))]?.slice()||null:null;if(d?.id==='sorcerer'&&allowance){if(hasAlternateFeature(c,'sorcerer-domain-access'))allowance=allowance.map((n,i)=>i?Math.max(0,n-1):n);if(hasAlternateFeature(c,'sorcerer-poltergeists'))allowance[0]=Math.max(0,allowance[0]-2);if(hasAlternateFeature(c,'sorcerer-stalwart-sorcerer')){const highest=allowance.findLastIndex(n=>n>1);if(highest>0&&allowance[highest]>1)allowance[highest]--;}}return {...r,slots,known:allowance,highest:row?.slots?.reduce((n,v,i)=>v!=null?i:n,-1)??-1};}
export function hitPoints(c:Character){const con=Math.floor((effectiveScore(c,'CON')-10)/2);return hitDieSequence(c).reduce((n,row,i)=>{const raw=i===0||c.automation.hpMethod==='maximum'?row.die:c.automation.hpMethod==='rolled'?Math.min(row.die,c.automation.history.find(h=>h.key===row.key)?.hitDieRoll??c.automation.hpRolls[i]??Math.ceil((row.die+1)/2)):((i%2===1)?Math.ceil((row.die+1)/2):Math.floor((row.die+1)/2));return n+Math.max(1,raw+con)},0)+(monkStyleBonus(c,'Kyokushinkai Karate')?6:0)+(hasAlternateFeature(c,'barbarian-totem-manifestation')&&alternateSettings(c,'barbarian-totem-manifestation').choice==='Bear'?classLevel(c,'barbarian'):0)+3*featCount(c,'Toughness')+(hasAlternateFeature(c,'sorcerer-stalwart-sorcerer')?2*classLevel(c,'sorcerer'):0);}
export function advancementNumbers(c:Character){const hd=classTotals(c.classLevels,c.ancestry,c).level||c.level,ecl=hd+(c.ancestry.ignoreLevelAdjustment?0:c.ancestry.levelAdjustment);const human=racialBonusFeat(c);const sequence=hitDieSequence(c);const ledger=c.automation.enabled&&c.automation.skillTraining.version===1?skillLedger(c):null;const budget=ledger?.granted??sequence.reduce((n,row,i)=>n+skillPointGrant(c,row,i),0);const spent=ledger?.spent??c.skills.reduce((n,s)=>n+s.ranks*(s.classSkill?1:2),0);const fighter=classLevel(c,'fighter'),wizard=classLevel(c,'wizard'),psion=classLevel(c,'psion'),pw=classLevel(c,'psychic-warrior');return {hd,ecl,nextXp:ecl*(ecl+1)*500,xpRemaining:Math.max(0,ecl*(ecl+1)*500-c.experience),classMax:hd+3,crossMax:(hd+3)/2,skillBudget:budget,skillSpent:spent,skillRemaining:budget-spent,feats:1+Math.floor(hd/3)+(human?1:0),fighterFeats:Array.from({length:fighter},(_,i)=>i+1).filter(l=>(l===1||l%2===0)&&!featureReplaced(c,'fighter','bonus-feat',l)).length,wizardFeats:Array.from({length:wizard},(_,i)=>i+1).filter(l=>l%5===0&&!featureReplaced(c,'wizard','bonus-feat',l)).length,psionicFeats:Array.from({length:psion},(_,i)=>i+1).filter(l=>(l===1||l%5===0)&&!featureReplaced(c,'psion','bonus-feat',l)).length+Array.from({length:pw},(_,i)=>i+1).filter(l=>(l===1||l>=2&&(l-2)%3===0)&&!featureReplaced(c,'psychic-warrior','bonus-feat',l)).length,abilityIncreases:Math.floor(hd/4)};}
export function skillExtras(c:Character,name:string){if(!c.automation.enabled)return 0;let n=hasFeat(c,'Skill Focus',name)?3:0;const pairs:Record<string,string[]>= {Acrobatic:['Jump','Tumble'],Agile:['Balance','Escape Artist'],Alertness:['Listen','Spot'],'Animal Affinity':['Handle Animal','Ride'],Athletic:['Climb','Swim'],Deceitful:['Disguise','Forgery'],'Deft Hands':['Sleight of Hand','Use Rope'],Diligent:['Appraise','Decipher Script'],Investigator:['Gather Information','Search'],MagicalAptitude:['Spellcraft','Use Magic Device'],Negotiator:['Diplomacy','Sense Motive'],NimbleFingers:['Disable Device','Open Lock'],Persuasive:['Bluff','Intimidate'],'Self-Sufficient':['Heal','Survival'],Stealthy:['Hide','Move Silently']};for(const [feat,names] of Object.entries(pairs))if(names.includes(name)&&hasFeat(c,feat.replace(/([a-z])([A-Z])/g,'$1 $2')))n+=2;const ranks=(s:string)=>(c.skills.find(k=>k.name===s)?.ranks||0)>=5;
 const synergy:Record<string,string[]>={'Knowledge (nature)':['Survival'],Diplomacy:['Bluff','Knowledge (nobility and royalty)','Sense Motive'],Intimidate:['Bluff'],'Sleight of Hand':['Bluff'],Jump:['Tumble'],Balance:['Tumble'],Tumble:['Jump'],Spellcraft:['Knowledge (arcana)'],Ride:['Handle Animal']};n+=(synergy[name]||[]).filter(ranks).length*2;if(name==='Jump')n+=c.speed>30?Math.floor((c.speed-30)/10)*4:-Math.floor((30-c.speed)/10)*6;if(name==='Concentration'&&hasFeat(c,'Combat Casting')&&['defensive-casting','grappled-casting'].includes(c.automation.context.skillUse))n+=4;
 const use=c.automation.context.skillUse;const conditional:Array<[string,string,string]>=[['Appraise','Craft','craft-item'],['Decipher Script','Use Magic Device','scroll'],['Use Magic Device','Decipher Script','scroll'],['Use Magic Device','Spellcraft','scroll'],['Disguise','Bluff','acting'],['Survival','Knowledge (nature)','woodland'],['Escape Artist','Use Rope','bonds'],['Climb','Use Rope','rope'],['Search','Knowledge (architecture and engineering)','secret-door'],['Survival','Search','tracking'],['Survival','Knowledge (dungeoneering)','underground'],['Survival','Knowledge (geography)','navigation'],['Survival','Knowledge (the planes)','other-plane']];for(const [target,source,context] of conditional)if(name===target&&use===context&&ranks(source))n+=2;return n;}
