import type {Character,Caster,Psionic} from './model.ts';
import {findClass,spellSlots,isClassSkill,classTotals} from './classes.ts';
import {effectiveScore,racialTraits} from './ancestry.ts';
import {classLevel,featCount,hasFeat} from './effects.ts';
import known from './spells-known.json' with {type:'json'};
export const arcaneClasses=['wizard','sorcerer','bard','assassin'];
export function castingDefinition(p:Caster){return findClass(p.casting?.classId||p.name)||findClass(p.list);}
export function manifestDefinition(p:Psionic){return findClass(p.manifesting?.classId||p.name);}
export function advanceTargets(c:Character,e:Character['classLevels'][number]){const definition=findClass(e.classId);const texts=definition?.levels.filter(r=>r.level<=e.level).map(r=>[r.special,...r.extra].join(' '))||[];const text=texts.join(' ');const dual=e.classId==='mystic-theurge',psi=/manifesting/.test(text);return {spell:/existing.*(?:spellcasting|arcane)|existing class/.test(text),divine:dual||e.classId==='hierophant',psi,arcane:/arcane/.test(text),spellLevels:texts.filter(t=>/\+1\s*level of existing/.test(t)&&!(/^.*manifesting.*$/.test(t)&&!t.includes('spellcasting'))).length,psiLevels:texts.filter(t=>/\+1\s*level of existing manifesting/.test(t)).length};}
function selected(c:Character,e:Character['classLevels'][number],kind:'spell'|'divine'|'psi',arcane=false){const explicit=kind==='psi'?e.psionicTarget:kind==='divine'?e.divineTarget:e.castingTarget;if(explicit)return explicit==='none'?'':explicit;const candidates=kind==='psi'?c.psionics.filter(p=>p.manifesting?.classId!=='soulknife').map(p=>p.id):c.casters.filter(p=>!p.casting?.domain&&(!arcane||arcaneClasses.includes(castingDefinition(p)?.id||''))&&(kind!=='divine'||!arcaneClasses.includes(castingDefinition(p)?.id||''))).map(p=>p.id);return candidates.length===1?candidates[0]:'';}
export function casterProgression(c:Character,p:Caster):{progression:number;level:number;linked:boolean}{const d=castingDefinition(p);if(!d)return {progression:0,level:p.level,linked:false};const base=classLevel(c,d.id);let addition=0,clOnly=0;for(const e of c.classLevels){const t=advanceTargets(c,e);if(t.spell&&selected(c,e,'spell',t.arcane)===p.id)addition+=t.spellLevels;if(t.divine&&selected(c,e,'divine')===p.id){if(e.classId==='hierophant')clOnly+=e.level;else addition+=t.spellLevels;}}
 // Domain profiles follow the selected cleric tradition, including prestige advancement.
 if(p.casting?.domain){const primary=c.casters.find(q=>q.id!==p.id&&!q.casting?.domain&&castingDefinition(q)?.id===d.id);if(primary){const r=casterProgression(c,primary);return {...r,level:r.level+(p.casting.levelAdjustment||0)}}}
 const progression=p.casting?.progression??(base+addition);const level=(['paladin','ranger'].includes(d.id)?progression<4?0:Math.floor(progression/2):progression)+clOnly+(p.casting?.levelAdjustment||0);return {progression,level,linked:base>0||p.casting?.progression!=null};}
export function psionicProgression(c:Character,p:Psionic){const d=manifestDefinition(p);if(!d)return {progression:0,level:p.level,linked:false};const base=classLevel(c,d.id);let extra=0;for(const e of c.classLevels){const t=advanceTargets(c,e);if(t.psi&&selected(c,e,'psi')===p.id)extra+=t.psiLevels;}const progression=p.manifesting?.progression??base+extra;return {progression,level:d.id==='soulknife'?0:progression+(p.manifesting?.levelAdjustment||0),linked:base>0||p.manifesting?.progression!=null};}
export function castingNumbers(c:Character,p:Caster){const d=castingDefinition(p),r=casterProgression(c,p);const score=effectiveScore(c,p.ability,true);const row=d?.levels.find(v=>v.level===Math.min(r.progression,d.levels.length));let slots=row?.slots?spellSlots(d!,row.level,score).map(s=>s.max):Array(10).fill(0);if(p.casting?.domain)slots=slots.map((_,i)=>i>0&&row?.slots?.[i]!=null&&score>=10+i?1:0);slots=slots.map((v,i)=>Math.max(0,v+(p.casting?.slotAdjustments[i]||0)));const knownTables=known as Record<string,Record<string,number[]>>;return {...r,slots,known:d?knownTables[d.id]?.[String(Math.min(r.progression,d.levels.length))]||null:null,highest:row?.slots?.reduce((n,v,i)=>v!=null?i:n,-1)??-1};}
export function hitDieSequence(c:Character){const rows:Array<{key:string,label:string,die:number,skillBase:number,classId:string,classLevel:number}>=[];for(let i=1;i<=c.ancestry.racialHitDice;i++)rows.push({key:'racial-'+i,label:'Racial HD '+i,die:8,skillBase:2,classId:'racial',classLevel:i});const entries=[...c.classLevels].sort((a,b)=>a.id===c.automation.firstClassId?-1:b.id===c.automation.firstClassId?1:0);for(const e of entries){const d=findClass(e.classId);for(let i=1;i<=e.level;i++)rows.push({key:e.id+'-'+i,label:e.name+' '+i,die:d?.hitDie||0,skillBase:d?.skillPoints||2,classId:e.classId,classLevel:i})}return rows;}
export function hitPoints(c:Character){const con=Math.floor((effectiveScore(c,'CON')-10)/2);return hitDieSequence(c).reduce((n,row,i)=>{const raw=i===0||c.automation.hpMethod==='maximum'?row.die:c.automation.hpMethod==='rolled'?Math.min(row.die,c.automation.hpRolls[i]||Math.ceil((row.die+1)/2)):((i%2===1)?Math.ceil((row.die+1)/2):Math.floor((row.die+1)/2));return n+Math.max(1,raw+con)},0)+3*featCount(c,'Toughness');}
export function advancementNumbers(c:Character){const hd=classTotals(c.classLevels,c.ancestry).level||c.level,ecl=hd+(c.ancestry.ignoreLevelAdjustment?0:c.ancestry.levelAdjustment);const human=racialTraits(c)?.id==='human';const sequence=hitDieSequence(c);const budget=sequence.reduce((n,row,i)=>{const history=c.automation.history.find(h=>h.key===row.key),int=history?.intScore??effectiveScore(c,'INT',true);return n+(history?.skillPoints??((Math.max(1,row.skillBase+Math.floor((int-10)/2))+(human?1:0))*(i===0?4:1)))},0);const spent=c.skills.reduce((n,s)=>n+s.ranks*(s.classSkill?1:2),0);const fighter=classLevel(c,'fighter'),wizard=classLevel(c,'wizard'),psion=classLevel(c,'psion'),pw=classLevel(c,'psychic-warrior');return {hd,ecl,nextXp:ecl*(ecl+1)*500,xpRemaining:Math.max(0,ecl*(ecl+1)*500-c.experience),classMax:hd+3,crossMax:(hd+3)/2,skillBudget:budget,skillSpent:spent,skillRemaining:budget-spent,feats:1+Math.floor(hd/3)+(human?1:0),fighterFeats:fighter?1+Math.floor(fighter/2):0,wizardFeats:Math.floor(wizard/5),psionicFeats:(psion?1+Math.floor(psion/5):0)+(pw?1+Math.floor((pw+1)/3):0),abilityIncreases:Math.floor(hd/4)};}
export function skillExtras(c:Character,name:string){if(!c.automation.enabled)return 0;let n=hasFeat(c,'Skill Focus',name)?3:0;const pairs:Record<string,string[]>= {Acrobatic:['Jump','Tumble'],Agile:['Balance','Escape Artist'],Alertness:['Listen','Spot'],'Animal Affinity':['Handle Animal','Ride'],Athletic:['Climb','Swim'],Deceitful:['Disguise','Forgery'],'Deft Hands':['Sleight of Hand','Use Rope'],Diligent:['Appraise','Decipher Script'],Investigator:['Gather Information','Search'],MagicalAptitude:['Spellcraft','Use Magic Device'],Negotiator:['Diplomacy','Sense Motive'],NimbleFingers:['Disable Device','Open Lock'],Persuasive:['Bluff','Intimidate'],'Self-Sufficient':['Heal','Survival'],Stealthy:['Hide','Move Silently']};for(const [feat,names] of Object.entries(pairs))if(names.includes(name)&&hasFeat(c,feat.replace(/([a-z])([A-Z])/g,'$1 $2')))n+=2;const ranks=(s:string)=>(c.skills.find(k=>k.name===s)?.ranks||0)>=5;
 const synergy:Record<string,string[]>={Diplomacy:['Bluff','Knowledge (nobility and royalty)','Sense Motive'],Intimidate:['Bluff'],'Sleight of Hand':['Bluff'],Jump:['Tumble'],Balance:['Tumble'],Tumble:['Jump'],Spellcraft:['Knowledge (arcana)'],Survival:['Knowledge (nature)'],Ride:['Handle Animal']};n+=(synergy[name]||[]).filter(ranks).length*2;if(name==='Jump')n+=c.speed>30?Math.floor((c.speed-30)/10)*4:-Math.floor((30-c.speed)/10)*6;if(name==='Concentration'&&hasFeat(c,'Combat Casting')&&['defensive-casting','grappled-casting'].includes(c.automation.context.skillUse))n+=4;
 const use=c.automation.context.skillUse;const conditional:Array<[string,string,string]>=[['Appraise','Craft','craft-item'],['Decipher Script','Use Magic Device','scroll'],['Use Magic Device','Decipher Script','scroll'],['Use Magic Device','Spellcraft','scroll'],['Disguise','Bluff','acting'],['Handle Animal','Survival','tracking'],['Escape Artist','Use Rope','bonds'],['Climb','Use Rope','rope'],['Search','Knowledge (architecture and engineering)','secret-door'],['Survival','Search','tracking'],['Survival','Knowledge (dungeoneering)','underground'],['Survival','Knowledge (geography)','navigation'],['Survival','Knowledge (the planes)','other-plane']];for(const [target,source,context] of conditional)if(name===target&&use===context&&ranks(source))n+=2;return n;}
