import {effectBonus,classAbilityBonus} from './effects.ts';
import data from './race-data.json' with {type:'json'};
import type {Character,Skill} from './model.ts';
type Ability='STR'|'DEX'|'CON'|'INT'|'WIS'|'CHA';
export type RaceDefinition={id:string,name:string,group:string,abilities:Partial<Record<Ability,number>>,size:Character['size'],speed:number,type:string,vision:string,languages:string[],bonusLanguages:string,favoredClass:string,la:number,rhd:number,hitDice:string,natural:number,dodge:number,skills:Record<string,number>,saves:Partial<Record<'fort'|'ref'|'will',number>>,powerPoints:number,grapple:number,traits:string[],source:string,book:string,openGame:boolean,reference?:string};
export const raceCatalog=data as RaceDefinition[];
export const findRace=(id:string)=>raceCatalog.find(r=>r.id===id);
export function racialAbility(c:Character,a:Ability){const delta=c.ancestry.abilityAdjustments?(findRace(c.ancestry.raceId)?.abilities[a]||0):0;return c.ancestry.abilityAdjustments&&c.ancestry.raceId==='half-orc'&&a==='INT'?Math.max(3,c.scores[a]+delta)-c.scores[a]:delta;}
export function effectiveScore(c:Character,a:Ability,lasting=false){return c.scores[a]+racialAbility(c,a)+(lasting?0:c.temps[a])+classAbilityBonus(c,a)+effectBonus(c,a,{},lasting);}
export function racialHDProgression(a?:Character['ancestry']){const n=a?.racialHitDice||0;if(!n)return {level:0,bab:0,fort:0,ref:0,will:0,missing:[] as string[]};const r=a&&findRace(a.raceId);if(!r||!['gnoll','lizardfolk'].includes(r.id))return {level:n,bab:0,fort:0,ref:0,will:0,missing:['Custom racial Hit Dice']};return {level:n,bab:Math.floor(n*.75),fort:r.id==='gnoll'?2+Math.floor(n/2):Math.floor(n/3),ref:r.id==='lizardfolk'?2+Math.floor(n/2):Math.floor(n/3),will:Math.floor(n/3),missing:[] as string[]};}
export function racialTraits(c:Character){return c.ancestry.traitBonuses?findRace(c.ancestry.raceId):undefined;}
export function racialSkill(c:Character,s:Pick<Skill,'name'>){const r=racialTraits(c);const exact=r?.skills[s.name]||0;const specialty=s.name.includes(' (')?(r?.skills[s.name.split(' (')[0]]||0):0;const hide=s.name==='Hide'?({Fine:16,Diminutive:12,Tiny:8,Small:4,Medium:0,Large:-4,Huge:-8,Gargantuan:-12,Colossal:-16}[c.size]):0;return exact+specialty+hide;}
export function racialPowerPoints(c:Character){return racialTraits(c)?.powerPoints||0;}
export function racialSummary(c:Character){const r=findRace(c.ancestry.raceId);if(!r)return '';return [r.type+'; '+r.size+'; base land speed '+r.speed+' ft.; '+r.vision,'Ability adjustments: '+(Object.entries(r.abilities).map(([k,v])=>k+' '+(v!>=0?'+':'')+v).join(', ')||'None'),'Racial HD: '+r.hitDice+'; level adjustment +'+r.la,'Automatic languages: '+r.languages.join(', '),'Unconditional racial bonuses: '+([...Object.entries(r.skills).map(([k,n])=>k+' +'+n),...Object.entries(r.saves).map(([k,n])=>k+' saves +'+n),...(r.natural?['Natural armor +'+r.natural]:[]),...(r.dodge?['Dodge AC +'+r.dodge]:[]),...(r.grapple?['Powerful build grapple +'+r.grapple]:[]),...(r.powerPoints?['Power points +'+r.powerPoints]:[])].join('; ')||'None'),...r.traits,'Source: '+r.book+' — '+r.source].join('\n\n');}
export function copyRacialTraits(c:Character){const r=findRace(c.ancestry.raceId);if(!r)return;const id='race-reference';const f=c.features.find(x=>x.id===id);if(f){f.name=r.name+' racial traits';f.description=racialSummary(c);f.source=r.source;}else c.features.push({id,name:r.name+' racial traits',kind:'Racial trait',description:racialSummary(c),max:0,used:0,source:r.source});}
export function selectRace(c:Character,id:string,options:{abilities:boolean,traits:boolean,body:boolean,languages:boolean,speedBonus?:number}){const r=findRace(id);if(!r)throw new Error('Choose a race from the library.');c.race=r.name;c.ancestry={...c.ancestry,raceId:id,abilityAdjustments:options.abilities,traitBonuses:options.traits,racialHitDice:r.rhd,levelAdjustment:r.la};if(options.body){if(c.automation){c.automation.baseSize=r.size;c.automation.baseSpeed=r.speed;}c.size=r.size;c.speed=Math.max(0,r.speed+(options.speedBonus||0));}if(options.languages){const known=c.languages.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);for(const language of r.languages)if(!known.some(x=>x.toLowerCase()===language.toLowerCase()))known.push(language);c.languages=known.join(', ');}copyRacialTraits(c);}
