import {clearRacialState} from './racial-abilities.ts';
import {effectBonus,classAbilityBonus} from './effects.ts';
import extra from './ultimate-race-data.json' with {type:'json'};
import references from './race-reference-data.json' with {type:'json'};
import sourceUrls from './race-source-urls.json' with {type:'json'};
import {creatureProfileSchema} from './creature-schema.ts';
import data from './race-data.json' with {type:'json'};
import type {Character,Skill} from './model.ts';
type Ability='STR'|'DEX'|'CON'|'INT'|'WIS'|'CHA';
export type RacialProgression={type:string,die:number,bab:number,goodSaves:Array<'fort'|'ref'|'will'>,skillBase:number,classSkills:string[]};
export type RaceDefinition={entryKind?:'race'|'reference'|'template',imported?:boolean,manualHandling?:string[],parentSource?:string,bonusFeat?:boolean,bonusSkillPoints?:number,alwaysClassSkills?:string[],nonabilities?:Ability[],fly?:number,climb?:number,burrow?:number,racialProgression?:RacialProgression,baseRace?:string,element?:string,swim?:number,waterBreathing?:boolean,id:string,name:string,group:string,abilities:Partial<Record<Ability,number>>,size:Character['size'],speed:number,type:string,vision:string,languages:string[],bonusLanguages:string,favoredClass:string,la:number,rhd:number,hitDice:string,natural:number,dodge:number,skills:Record<string,number>,saves:Partial<Record<'fort'|'ref'|'will',number>>,powerPoints:number,grapple:number,traits:string[],source:string,book:string,openGame:boolean,reference?:string};
export const raceCatalog:RaceDefinition[]=[...data.map(r=>({...r,source:(sourceUrls as Record<string,string>)[r.id]||r.source})),...extra] as RaceDefinition[];
export const raceReferenceCatalog=references as RaceDefinition[];
export const racialBonusFeat=(c:Character)=>!!(racialTraits(c)?.bonusFeat??(racialTraits(c)?.id==='human'));
export const racialBonusSkillPoints=(c:Character)=>racialTraits(c)?.bonusSkillPoints??(racialTraits(c)?.id==='human'?1:0);
export function raceProgression(id:string):RacialProgression|undefined {return findRace(id)?.racialProgression||({gnoll:{type:'Humanoid',die:8,bab:.75,goodSaves:['fort'],skillBase:2,classSkills:['Climb','Listen','Spot']},lizardfolk:{type:'Humanoid',die:8,bab:.75,goodSaves:['ref'],skillBase:2,classSkills:['Balance','Jump','Swim']}} as Record<string,RacialProgression>)[id];}

export const findRace=(id:string)=>raceCatalog.find(r=>r.id===id);
export function racialAbility(c:Character,a:Ability){const delta=c.ancestry.abilityAdjustments?(findRace(c.ancestry.raceId)?.abilities[a]||0):0;return c.ancestry.abilityAdjustments&&['half-orc','water-half-orc'].includes(c.ancestry.raceId)&&a==='INT'?Math.max(3,c.scores[a]+delta)-c.scores[a]:delta;}
// Numeric compatibility for legacy formulas; creatureAbilityScore exposes absence as null.
export function effectiveScore(c:Character,a:Ability,lasting=false){if(c.creature?.nonabilities.includes(a))return 10;return c.scores[a]+racialAbility(c,a)+(lasting?0:c.temps[a])+classAbilityBonus(c,a)+effectBonus(c,a,{},lasting);}
export function racialHDProgression(a?:Character['ancestry']){const n=a?.racialHitDice||0,p=a&&raceProgression(a.raceId);const save=(s:'fort'|'ref'|'will')=>n&&p?(p.goodSaves.includes(s)?2+Math.floor(n/2):Math.floor(n/3)):0;return {level:n,die:p?.die||8,bab:Math.floor(n*(p?.bab||0)),fort:save('fort'),ref:save('ref'),will:save('will'),missing:n&&!p?['Custom racial Hit Dice']:[] as string[]};}
export function racialTraits(c:Character){return c.ancestry.traitBonuses?findRace(c.ancestry.raceId):undefined;}
export function racialSkill(c:Character,s:Pick<Skill,'name'>){const r=racialTraits(c);const exact=r?.skills[s.name]||0;const specialty=s.name.includes(' (')?(r?.skills[s.name.split(' (')[0]]||0):0;const hide=s.name==='Hide'?({Fine:16,Diminutive:12,Tiny:8,Small:4,Medium:0,Large:-4,Huge:-8,Gargantuan:-12,Colossal:-16}[c.size]):0;return exact+specialty+hide;}
export function racialPowerPoints(c:Character){return racialTraits(c)?.powerPoints||0;}
export function racialSummary(c:Character){const r=findRace(c.ancestry.raceId);if(!r)return '';return [r.type+'; '+r.size+'; base land speed '+r.speed+' ft.; '+r.vision,'Ability adjustments: '+(Object.entries(r.abilities).map(([k,v])=>k+' '+(v!>=0?'+':'')+v).join(', ')||'None'),'Racial HD: '+r.hitDice+'; level adjustment +'+r.la,'Automatic languages: '+r.languages.join(', '),'Unconditional racial bonuses: '+([...Object.entries(r.skills).map(([k,n])=>k+' +'+n),...Object.entries(r.saves).map(([k,n])=>k+' saves +'+n),...(r.natural?['Natural armor +'+r.natural]:[]),...(r.dodge?['Dodge AC +'+r.dodge]:[]),...(r.grapple?['Powerful build grapple +'+r.grapple]:[]),...(r.powerPoints?['Power points +'+r.powerPoints]:[])].join('; ')||'None'),...r.traits,...(r.manualHandling||[]),...(r.parentSource?['Parent rules: '+r.parentSource]:[]),'Source: '+r.book+' — '+r.source].join('\n\n');}
export function copyRacialTraits(c:Character){const r=findRace(c.ancestry.raceId);if(!r)return;const id='race-reference';const f=c.features.find(x=>x.id===id);if(f){f.name=r.name+' racial traits';f.description=racialSummary(c);f.source=r.source;}else c.features.push({id,name:r.name+' racial traits',kind:'Racial trait',description:racialSummary(c),max:0,used:0,source:r.source});}
export function selectRace(c:Character,id:string,options:{abilities:boolean,traits:boolean,body:boolean,languages:boolean,speedBonus?:number}){const r=findRace(id);if(!r)throw new Error('Choose a race from the library.');if(c.ancestry.raceId!==id)clearRacialState(c);c.race=r.name;c.ancestry={...c.ancestry,raceId:id,abilityAdjustments:options.abilities,traitBonuses:options.traits,racialHitDice:r.rhd,levelAdjustment:r.la};if(options.body){if(c.creature?.raceOrigin&&c.creature.raceOrigin!==id)c.creature=null;if(r.imported&&c.sheetKind!=='monster'&&!c.creature){const p=r.racialProgression;c.creature=creatureProfileSchema.parse({raceOrigin:id,type:p?.type||'Humanoid',racialHitDice:0,nonabilities:r.nonabilities||[],source:r.source,senses:r.vision,movement:{swim:r.swim||0,fly:r.fly||0,climb:r.climb||0,burrow:r.burrow||0},notes:'Race-derived profile. Racial progression uses Race → racial Hit Dice. Special traits require the linked source.'});}if(c.automation){c.automation.baseSize=r.size;c.automation.baseSpeed=r.speed;}c.size=r.size;c.speed=Math.max(0,r.speed+(options.speedBonus||0));}if(options.languages){const known=c.languages.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);for(const language of r.languages)if(!known.some(x=>x.toLowerCase()===language.toLowerCase()))known.push(language);c.languages=known.join(', ');}copyRacialTraits(c);}
