import type {Character} from './model.ts';
import {defaultAutomation} from './automation-schema.ts';
import {findClass,classTotals,applyClassTotals,inferClassEntries,makeCaster,makePsionic} from './classes.ts';
import {effectiveScore,racialTraits} from './ancestry.ts';
import {effectBonus,effectActive,classLevel,featCount,hasFeat,baseVariables} from './effects.ts';
import {equippedArmor,carrying,movement,matchEquipment,equipmentById,gearWeight,allSizes} from './equipment.ts';
import {castingDefinition,castingNumbers,manifestDefinition,psionicProgression,hitDieSequence,hitPoints,advanceTargets} from './advancement.ts';
import {expression,expandFormula} from './formulas.ts';
export const calculationFields:Array<[string,string]>=[['maxHp','Maximum HP'],['speed','Speed'],['bab','Base attack'],['defense.armor','Armor bonus'],['defense.shield','Shield bonus'],['defense.dexCap','Maximum Dexterity bonus'],['defense.checkPenalty','Armor check penalty'],['defense.spellFailure','Arcane spell failure'],['defense.sr','Spell resistance'],['saves.fort.base','Base Fortitude'],['saves.ref.base','Base Reflex'],['saves.will.base','Base Will']];
function read(c:Character,path:string){return path.split('.').reduce((v,k)=>v?.[k],c as any) as number;}
function assign(c:Character,path:string,n:number){const keys=path.split('.'),last=keys.pop()!;const object=keys.reduce((o,k)=>o[k],c as any);object[last]=n;}
function number(c:Character,path:string,value:number){const result=c.automation.overrides[path]??value+(c.automation.adjustments[path]||0);const bounded=path==='defense.checkPenalty'?Math.min(0,Math.max(-100,result)):path==='defense.dexCap'?Math.min(100,Math.max(-100,result)):path==='defense.spellFailure'?Math.min(100,Math.max(0,result)):['maxHp','speed','defense.sr'].includes(path)?Math.min(10000,Math.max(0,Math.round(result))):result;assign(c,path,bounded);}
export function formulaVariables(c:Character,extra:Record<string,number>={}){const v=baseVariables(c);for(const a of ['STR','DEX','CON','INT','WIS','CHA'] as const){v[a]=effectiveScore(c,a);v[a+'_MOD']=Math.floor((v[a]-10)/2)}return {...v,...extra};}
export function diceFormula(c:Character,input:string,extra:Record<string,number>={}){return expandFormula(input,formulaVariables(c,extra));}
export function formulaPreview(c:Character,input:string,extra:Record<string,number>={}){try{return {formula:diceFormula(c,input,extra),error:''}}catch(e){return {formula:'',error:e instanceof Error?e.message:'Invalid formula'}}}
export function resourceNumbers(c:Character){const lv=(id:string)=>classLevel(c,id),cha=Math.floor((effectiveScore(c,'CHA')-10)/2),con=Math.floor((effectiveScore(c,'CON')-10)/2);const barb=lv('barbarian'),pal=lv('paladin'),monk=lv('monk'),druid=lv('druid'),dd=lv('dragon-disciple');return {rageUses:barb?1+Math.floor(barb/4):0,rageRounds:Math.max(1,3+con+(effectActive(c,'rage')?0:barb>=20?4:barb>=11?3:2)),turnLevel:lv('cleric')+Math.max(0,pal-3)+(hasFeat(c,'Improved Turning')?1:0),turnCheck:cha+((c.skills.find(s=>s.name==='Knowledge (religion)')?.ranks||0)>=5?2:0),turnDamage:lv('cleric')+Math.max(0,pal-3)+(hasFeat(c,'Improved Turning')?1:0)+cha,layHands:pal>=2?pal*Math.max(0,cha):0,smiteDamage:pal,smiteAttack:Math.max(0,cha),stunningDC:10+Math.floor(c.level/2)+Math.floor((effectiveScore(c,'WIS')-10)/2),sneakDice:Math.ceil(lv('rogue')/2)+Math.ceil(lv('assassin')/2)+Math.floor(lv('arcane-trickster')/2)+Math.floor(Math.max(0,lv('blackguard')-1)/3),deathAttackDC:10+lv('assassin')+Math.floor((effectiveScore(c,'INT')-10)/2),breathDice:dd>=10?6:dd>=7?4:dd>=3?2:0,breathDC:10+dd+con,monkLevel:monk+lv('psionic-fist'),wildShape:druid<5?0:druid<6?1:druid<7?2:druid<10?3:druid<14?4:druid<18?5:6};}
function dailyResources(c:Character){const lv=(s:string)=>classLevel(c,s),r=resourceNumbers(c),cha=Math.floor((effectiveScore(c,'CHA')-10)/2);const resources:Array<[string,number,string]>=[];const add=(condition:number|boolean,name:string,max:number,note:string)=>{if(condition)resources.push([name,Math.max(0,max),note])};add(lv('barbarian'),'Rage',r.rageUses,'Activate Rage under Effects. Duration: '+r.rageRounds+' rounds.');add(lv('bard'),'Bardic music',lv('bard'),'Daily music uses; choose the performance and targets.');add(r.turnLevel,'Turn or rebuke undead',3+cha+4*featCount(c,'Extra Turning'),'Effective turning level '+r.turnLevel+'.');add(lv('paladin')>=2,'Lay on hands — healing points',r.layHands,'Used today is the number of healing points spent.');add(lv('paladin'),'Smite evil',1+Math.floor(lv('paladin')/5),'Attack bonus +'+r.smiteAttack+'; damage +'+r.smiteDamage+' against evil.');add(lv('druid')>=5,'Wild shape',r.wildShape,'Duration '+lv('druid')+' hours. Form changes require choosing the form’s statistics.');add(lv('druid')>=16,'Elemental wild shape',lv('druid')>=20?3:lv('druid')>=18?2:1,'Separate from animal wild shape uses.');add(lv('monk')>=7,'Wholeness of body — healing points',2*lv('monk'),'Healing points per day.');add(hasFeat(c,'Stunning Fist'),'Stunning Fist',lv('monk')+Math.floor((c.level-lv('monk'))/4),'Fortitude DC '+r.stunningDC+'.');add(lv('monk')>=12,'Abundant step',1,'Dimension door; caster level '+Math.floor(lv('monk')/2)+'.');add(lv('blackguard')>=2,'Smite good',lv('blackguard')>=10?3:lv('blackguard')>=5?2:1,'Attack +'+Math.max(0,cha)+', damage +'+lv('blackguard')+'.');add(lv('blackguard')>=3,'Command undead',3+cha+4*featCount(c,'Extra Turning'),'Effective turning level '+(lv('blackguard')-2)+'.');add(lv('dragon-disciple')>=3,'Dragon breath',1,r.breathDice+'d8 damage; save DC '+r.breathDC+'.');add(lv('dwarven-defender'),'Defensive stance',Math.ceil(lv('dwarven-defender')/2),'Choose a stance effect for its ability, save, and AC changes.');add(lv('arcane-trickster'),'Ranged legerdemain',1+Math.floor((lv('arcane-trickster')-1)/4),'Uses per day.');add(lv('arcane-trickster')>=3,'Impromptu sneak attack',lv('arcane-trickster')>=7?2:1,'Uses per day.');add(lv('shadowdancer')>=4,'Shadow jump — feet',20*Math.pow(2,Math.floor((lv('shadowdancer')-4)/2)),'Distance available each day; minimum 10 feet per jump.');
 const race=racialTraits(c)?.id;const sla:Record<string,string[]>={drow:['Dancing lights','Darkness','Faerie fire'],duergar:['Enlarge person','Invisibility'],'deep-gnome':['Blindness/deafness','Blur','Disguise self'],aasimar:['Daylight'],tiefling:['Darkness'],'whisper-gnome':['Silence']};for(const name of sla[race||'']||[])add(true,name+' — racial',1,'Racial spell-like ability; see Race for caster level and restrictions.');
 const keep=new Set(resources.map(([name])=>name));c.features=c.features.filter(f=>!f.ruleId?.startsWith('daily:')||keep.has(f.name));for(const [name,max,description] of resources){let f=c.features.find(f=>f.name===name);if(!f){f={id:crypto.randomUUID(),name,kind:'Class feature',description,max,used:0,source:'https://olimot.github.io/srd-v3.5/basic-rules-and-legal/character-classes-i.html',ruleId:'daily:'+name};c.features.push(f)}f.max=Math.min(10000,max);f.ruleId='daily:'+name;f.description=description;}
 for(const f of c.features)if(f.formula){try{f.max=Math.min(10000,Math.max(0,Math.floor(expression(f.formula,formulaVariables(c)))))}catch{/* An unfinished expression keeps the last valid result. */}}
}
export function recompute(c:Character,previous?:Character){if(!c.automation.enabled)return c;const oldMax=previous?.maxHp??c.maxHp;const t=classTotals(c.classLevels,c.ancestry);if(t.level&&t.level<=100&&!t.missing.length){applyClassTotals(c);number(c,'bab',t.bab);for(const s of ['fort','ref','will'] as const)number(c,'saves.'+s+'.base',t[s]);}
 const base=allSizes.indexOf(c.automation.baseSize);c.size=allSizes[Math.max(0,Math.min(8,base+Math.trunc(effectBonus(c,'size'))))];
 for(const g of c.gear)if(g.catalogId){g.weight=gearWeight(c,g);if(g.weaponId){const w=c.weapons.find(w=>w.id===g.weaponId);if(w){w.enhancement=g.enhancement||0;w.masterwork=g.masterwork||false}}}
 const a=equippedArmor(c),load=carrying(c);number(c,'defense.armor',a.armor);number(c,'defense.shield',a.shield);number(c,'defense.dexCap',Math.min(a.dexCap,c.automation.encumbrance?load.dexCap:100));number(c,'defense.checkPenalty',Math.min(a.checkPenalty,c.automation.encumbrance?load.checkPenalty:0));number(c,'defense.spellFailure',a.spellFailure);c.speed=movement(c).speed;
 const race=racialTraits(c);const sr=Math.max(['drow','deep-gnome'].includes(race?.id||'')?11+c.classLevels.reduce((n,x)=>n+x.level,0):0,classLevel(c,'monk')>=13?10+classLevel(c,'monk'):0,effectBonus(c,'sr'));number(c,'defense.sr',sr);
 const sequence=hitDieSequence(c);c.automation.history=sequence.map(r=>c.automation.history.find(h=>h.key===r.key)||{key:r.key,intScore:effectiveScore(c,'INT',true),...(c.automation.hpRolls[sequence.indexOf(r)]?{hitDieRoll:c.automation.hpRolls[sequence.indexOf(r)]}:{})});
 if(!t.missing.length&&sequence.length){number(c,'maxHp',hitPoints(c));c.hp+=c.maxHp-oldMax;}
 for(const p of c.casters){if(!p.casting){const d=castingDefinition(p);if(d)p.casting={classId:d.id,domain:false,progression:null,levelAdjustment:0,slotAdjustments:Array(10).fill(0),automatic:true};}if(p.casting?.automatic){const r=castingNumbers(c,p);if(castingDefinition(p)){p.level=Math.max(0,Math.min(100,r.level));p.slots=p.slots.map((s,i)=>({...s,max:Math.min(10000,r.slots[i])}))}}}
 const limitedBonus=c.psionics.some(p=>['psionic-fist','war-mind'].includes(manifestDefinition(p)?.id||''));const highest=[...c.psionics].sort((a,b)=>psionicProgression(c,b).level-psionicProgression(c,a).level)[0]?.id;
 for(const p of c.psionics){if(!p.manifesting){const d=manifestDefinition(p);if(d)p.manifesting={classId:d.id,progression:null,levelAdjustment:0,pointsAdjustment:0,automatic:true};}if(p.manifesting?.automatic){const d=manifestDefinition(p),r=psionicProgression(c,p);if(d){p.level=Math.max(0,Math.min(100,r.level));const row=d.levels.find(v=>v.level===Math.min(r.progression,d.levels.length));const bonus=limitedBonus&&p.id!==highest?0:Math.max(0,Math.floor(Math.floor((effectiveScore(c,p.ability,true)-10)/2)*p.level/2));p.max=Math.max(0,Math.min(10000,Math.floor((d.id==='soulknife'?(r.progression>0?2:0):(r.progression>0?row?.powerPoints||0:0)+bonus)+p.manifesting.pointsAdjustment)));}}}
 dailyResources(c);return c;}
export function activateAutomation(c:Character,preserve=true){if(c.automation.version===1)return recompute(c);const before=structuredClone(c);c.automation={...defaultAutomation(),version:1,enabled:true,baseSize:c.size,baseSpeed:c.speed,firstClassId:c.classLevels[0]?.id||''};if(!c.classLevels.length)c.classLevels=inferClassEntries(c.classes);const barb=classLevel(c,'barbarian'),monk=classLevel(c,'monk');c.automation.baseSpeed=Math.max(0,c.speed-(barb?10:0)-Math.floor(monk/3)*10);
 for(const g of c.gear){const e=matchEquipment(g.name);if(e)g.catalogId=e.id;}for(const w of c.weapons){const e=matchEquipment(w.name,'weapon');if(e){w.catalogId=e.id;w.diceSize=c.size;}const g=c.gear.find(g=>g.name.toLowerCase()===w.name.toLowerCase());if(g)g.weaponId=w.id;}
 if(!preserve){if(monk)c.defense.misc=0;if(classLevel(c,'paladin')>=2)c.saves.fort.misc=c.saves.ref.misc=c.saves.will.misc=0;}
 recompute(c);if(preserve){for(const [path] of calculationFields){const offset=read(before,path)-read(c,path);if(offset)c.automation.adjustments[path]=offset;}for(const p of c.casters){const old=before.casters.find(q=>q.id===p.id);if(old&&p.casting){p.casting.levelAdjustment+=old.level-p.level;p.casting.slotAdjustments=old.slots.map((s,i)=>s.max-p.slots[i].max)}}for(const p of c.psionics){const old=before.psionics.find(q=>q.id===p.id);if(old&&p.manifesting){p.manifesting.levelAdjustment+=old.level-p.level;p.manifesting.pointsAdjustment+=old.max-p.max;}}
 // The earlier starter stored these class bonuses directly in misc fields.
 if(monk)c.defense.misc-=Math.floor((effectiveScore(before,'WIS')-10)/2)+Math.floor(monk/5);if(classLevel(c,'paladin')>=2){const bonus=Math.max(0,Math.floor((effectiveScore(before,'CHA')-10)/2));for(const s of ['fort','ref','will'] as const)c.saves[s].misc-=bonus;}recompute(c);c.hp=before.hp;}return c;}
export function calculationWarnings(c:Character){if(!c.automation.enabled)return [];const warnings:string[]=[];const t=classTotals(c.classLevels,c.ancestry);if(t.missing.length)warnings.push('Custom class or racial HD needs manual base totals: '+t.missing.join(', '));if(!c.classLevels.length)warnings.push('Add class levels in Classes to calculate advancement.');if(equippedArmor(c).multiple)warnings.push('More than one armor or shield is equipped. Only the highest bonus of each is used; unequip the others.');for(const p of c.casters){if(p.casting?.automatic&&!castingNumbers(c,p).linked)warnings.push(p.name+': select its class in Classes or enter a progression override.');const r=castingNumbers(c,p);if(r.known)r.known.forEach((max,i)=>{if(p.spells.filter(k=>k.level===i).length>max)warnings.push(p.name+': more level '+i+' spells recorded than its '+max+' spells known.');});}
 for(const e of c.classLevels){const t=advanceTargets(c,e);if((t.spell&&c.casters.filter(p=>!p.casting?.domain).length>1&&!e.castingTarget)||(t.divine&&c.casters.filter(p=>!['wizard','sorcerer','bard','assassin'].includes(castingDefinition(p)?.id||'')).length>1&&!e.divineTarget)||(t.psi&&c.psionics.length>1&&!e.psionicTarget))warnings.push(e.name+': choose which tradition it advances under Calculations.');}
 for(const f of c.features)if(f.formula){try{expression(f.formula,formulaVariables(c))}catch(e){warnings.push(f.name+': '+(e instanceof Error?e.message:'invalid formula'))}}for(const e of c.effects.filter(e=>e.active))for(const m of e.modifiers){try{expression(m.value,{...baseVariables(c),CL:e.casterLevel})}catch(error){warnings.push(e.name+': '+(error instanceof Error?error.message:'invalid formula'))}}return [...new Set(warnings)];}
