import raw from './class-data.json' with {type:'json'};
import {racialHDProgression} from './ancestry.ts';
import type {Character,ClassLevel,Caster,Psionic} from './model.ts';
export type ClassRow={level:number,bab:number,fort:number,ref:number,will:number,special:string,extra:string[],slots?:Array<number|null>,powerPoints?:number,powersKnown?:number,powerLevel?:number};
export type ClassDefinition={id:string,name:string,kind:'Core'|'Psionic'|'Prestige',hitDie:number,skillPoints:number,skills:string,alignment:string,requirements:string,headers:string[],levels:ClassRow[],source:string,description?:string};
export const classCatalog=raw as ClassDefinition[];
export const baseClasses=classCatalog.filter(c=>c.kind!=='Prestige');
export const findClass=(idOrName:string)=>classCatalog.find(c=>c.id===idOrName||c.name.toLowerCase()===idOrName.toLowerCase());
export function classRow(def:ClassDefinition,level:number){const row=def.levels.find(r=>r.level===level);if(!row)throw new Error(def.name+' has no level '+level+' in this table.');return row;}
export function classTotals(entries:ClassLevel[],ancestry?:Character['ancestry']){const racial=racialHDProgression(ancestry);let {level,bab,fort,ref,will}=racial;const dice:Record<number,number>=racial.level?{8:racial.level}:{};const missing:string[]=[...racial.missing];
 for(const e of entries){const d=findClass(e.classId);level+=e.level;if(!d){missing.push(e.name);continue}const r=d.levels.find(r=>r.level===e.level);if(!r){missing.push(e.name+' '+e.level);continue}bab+=r.bab;fort+=r.fort;ref+=r.ref;will+=r.will;dice[d.hitDie]=(dice[d.hitDie]||0)+e.level;}
 return {level,bab,fort,ref,will,hitDice:Object.entries(dice).map(([die,n])=>`${n}d${die}`).join(' + '),missing};
}
export function isClassSkill(name:string,definitions:ClassDefinition[]){return definitions.some(d=>{const text=d.skills.toLowerCase();if(name.startsWith('Knowledge (')){const specialty=name.slice(11,-1).toLowerCase();return /knowledge \(all/.test(text)||text.includes(specialty);}return text.includes(name.toLowerCase().replace(/ \(.*/,''));});}
export function applyClassTotals(c:Character){const t=classTotals(c.classLevels,c.ancestry);if(t.missing.length)throw new Error('Enter custom class totals manually. Unknown table: '+t.missing.join(', '));if(!t.level||t.level>100)throw new Error('Choose between 1 and 100 total class levels.');c.classes=c.classLevels.map(e=>e.name+' '+e.level).join(' / ');c.level=t.level;c.bab=t.bab;c.hitDice=t.hitDice;c.saves.fort.base=t.fort;c.saves.ref.base=t.ref;c.saves.will.base=t.will;const definitions=c.classLevels.map(e=>findClass(e.classId)).filter((d):d is ClassDefinition=>!!d);c.skills.forEach(s=>{s.classSkill=isClassSkill(s.name,definitions)||(c.ancestry.racialHitDice>0&&(c.ancestry.raceId==='lizardfolk'?['Balance','Jump','Swim']:c.ancestry.raceId==='gnoll'?['Climb','Listen','Spot']:[]).includes(s.name))});}
export function inferClassEntries(label:string):ClassLevel[]{const parts=label.split(/\s*\/\s*/);const result:ClassLevel[]=[];for(const part of parts){const m=part.trim().match(/^(.+?)\s+(\d+)$/);if(!m)return [];const def=findClass(m[1]);if(!def||!def.levels.some(r=>r.level===Number(m[2])))return [];result.push({id:crypto.randomUUID(),classId:def.id,name:def.name,level:Number(m[2]),notes:''});}return result;}
export function spellSlots(def:ClassDefinition,level:number,score:number){const r=classRow(def,level),mod=Math.floor((score-10)/2);return Array.from({length:10},(_,i)=>{const base=r.slots?.[i];return {max:base==null||score<10+i?0:base+(i>0&&mod>=i?1+Math.floor((mod-i)/4):0),used:0}});}
export function makeCaster(def:ClassDefinition,level=3,score=16):Caster {const arcane=['wizard','sorcerer','bard','assassin'].includes(def.id);return {id:crypto.randomUUID(),name:def.name,list:def.id==='wizard'||def.id==='sorcerer'?'Sorcerer / Wizard':def.name,ability:def.id==='wizard'||def.id==='assassin'?'INT':arcane?'CHA':'WIS',level:['paladin','ranger'].includes(def.id)?(level<4?0:Math.floor(level/2)):level,mode:['sorcerer','bard','assassin'].includes(def.id)?'spontaneous':'prepared',dcExtra:0,penetration:0,slots:spellSlots(def,level,score),spells:[],casting:{classId:def.id,domain:false,progression:null,levelAdjustment:0,slotAdjustments:Array(10).fill(0),automatic:true},notes:def.id==='cleric'?'Daily slots exclude domain slots. Add a separate Domain tradition for those restricted slots.':''};}
export function makePsionic(def:ClassDefinition,level=3,score=16):Psionic{const row=classRow(def,level),bonus=Math.max(0,Math.floor(Math.floor((score-10)/2)*level/2));return {id:crypto.randomUUID(),name:def.name,ability:def.id==='psion'?'INT':def.id==='wilder'?'CHA':'WIS',level:def.id==='soulknife'?0:level,max:def.id==='soulknife'?2:(row.powerPoints||0)+bonus,spent:0,focused:false,dcExtra:0,notes:def.id==='soulknife'?'Wild Talent supplies 2 power points but no powers or manifester level.':'Choose powers from your class list and discipline. The class table gives powers known and maximum power level.',powers:[],manifesting:{classId:def.id,progression:null,levelAdjustment:0,pointsAdjustment:0,automatic:true}};}
export function copyClassFeatures(c:Character){for(const e of c.classLevels){const d=findClass(e.classId);if(!d)continue;const description=d.levels.filter(r=>r.level<=e.level&&r.special&&r.special!=='—').map(r=>`Level ${r.level}: ${r.special}`).join('\n');const id='class-summary-'+e.id;const feature={id,name:d.name+' class features',kind:'Class feature' as const,description:description+'\n\nUse the latest improved version of a feature. Bonuses are entered in the relevant sheet fields.\nFull class reference: '+d.source,max:0,used:0,source:d.source};const previous=c.features.find(f=>f.id===id);if(previous){previous.description=feature.description;previous.name=feature.name;}else c.features.push(feature);}}
export function applyStartingClass(c:Character,kind:string,level:number){const def=findClass(kind);if(!def||def.kind==='Prestige')throw new Error('Choose a base class; add prestige classes in Classes.');classRow(def,level);
 c.classLevels=[{id:crypto.randomUUID(),classId:def.id,name:def.name,level,notes:''}];c.psionics=[];c.casters=[];c.features=[];
 if(def.id!=='fighter'){
  const spreads:Record<string,number[]>={barbarian:[16,12,14,10,10,8],bard:[10,14,12,12,10,16],cleric:[10,12,14,12,16,10],druid:[10,12,14,10,16,8],monk:[14,14,12,10,16,8],paladin:[16,10,12,8,14,14],ranger:[14,16,12,10,14,8],rogue:[10,16,12,14,10,12],sorcerer:[10,12,14,12,10,16],wizard:[10,12,14,16,10,10],psion:[8,12,14,16,10,12],'psychic-warrior':[16,12,14,10,16,8],soulknife:[16,14,14,10,12,8],wilder:[10,12,14,10,12,16]};
  const [STR,DEX,CON,INT,WIS,CHA]=spreads[def.id];c.scores={STR,DEX,CON,INT,WIS,CHA};c.race='Human';c.languages='Common';c.speed=def.id==='barbarian'?40:def.id==='monk'?30+Math.floor(level/3)*10:30;c.gear=[];c.defense={armor:0,shield:0,natural:0,deflection:0,dodge:0,misc:def.id==='monk'?Math.floor((WIS-10)/2)+Math.floor(level/5):0,dexCap:100,checkPenalty:0,spellFailure:0,sr:0,dr:'',resistances:''};
  const w=c.weapons[0];w.name=def.id==='monk'?'Unarmed strike':def.id==='soulknife'?'Mind blade':def.id==='barbarian'?'Greataxe':def.id==='paladin'?'Longsword':def.id==='ranger'?'Longbow':def.id==='rogue'||def.id==='bard'?'Short sword':'Quarterstaff';w.damage=def.id==='barbarian'?'1d12':def.id==='paladin'||def.id==='ranger'?'1d8':def.id==='monk'?(level<4?'1d6':level<8?'1d8':level<12?'1d10':level<16?'2d6':level<20?'2d8':'2d10'):'1d6';w.crit=def.id==='barbarian'||def.id==='ranger'?'20 / ×3':def.id==='paladin'||def.id==='rogue'||def.id==='bard'||def.id==='soulknife'?'19–20 / ×2':'20 / ×2';w.ability=def.id==='ranger'?'DEX':'STR';w.damageAbility=def.id==='ranger'?'none':'STR';w.strength=def.id==='barbarian'?'two':'one';w.range=def.id==='ranger'?'110 ft.':'Melee';
  if(def.id==='paladin')c.saves.fort.misc=c.saves.ref.misc=c.saves.will.misc=level>=2?Math.max(0,Math.floor((CHA-10)/2)):0;
 }
 applyClassTotals(c);c.experience=level*(level-1)*500;
 if(!(def.id==='fighter'&&level===3)){c.maxHp=Math.max(level,def.hitDie+Math.ceil((level-1)*(def.hitDie/2+.5))+Math.floor((c.scores.CON-10)/2)*level);c.hp=c.maxHp;}
 if(def.levels[0].slots&&(!['paladin','ranger'].includes(def.id)||level>=4)){const ability=def.id==='wizard'?'INT':['bard','sorcerer'].includes(def.id)?'CHA':'WIS';c.casters=[makeCaster(def,level,c.scores[ability])];}
 if(def.kind==='Psionic')c.psionics=[makePsionic(def,level,c.scores[def.id==='psion'?'INT':def.id==='wilder'?'CHA':'WIS'])];
 copyClassFeatures(c);
 const addUse=(name:string,max:number,description:string)=>c.features.push({id:crypto.randomUUID(),name,kind:'Class feature',description,max:Math.max(0,max),used:0,source:def.source});
 if(def.id==='barbarian')addUse('Rage',1+Math.floor(level/4),'Track uses here. Enter rage modifiers and duration on the sheet.');
 if(def.id==='bard')addUse('Bardic music',level,'Daily uses. Check the Perform ranks and class level required for each effect.');
 if(def.id==='cleric'||def.id==='paladin'&&level>=4)addUse('Turn or rebuke undead',3+Math.floor((c.scores.CHA-10)/2),'Track daily turning attempts; resolve turning level, check, and damage at the table.');
 if(def.id==='paladin'&&level>=2)addUse('Lay on hands — healing points',level*Math.max(0,Math.floor((c.scores.CHA-10)/2)),'Set Used today to the total number of healing points spent.');
 return c;
}
