import raw from './equipment-data.json' with {type:'json'};
import {findClass} from './classes.ts';
import type {Character,Weapon} from './model.ts';
import {effectiveScore,racialTraits} from './ancestry.ts';
import {classLevel,hasFeat,effectBonus,effectTerms,stackBonuses,effectActive} from './effects.ts';
export type Equipment={id:string,name:string,kind:'weapon'|'armor'|'shield',category:string,weight:number,price:number,source:string,damage?:string,small?:string,threat?:number,multiplier?:number,range?:number,ranged?:boolean,thrown?:boolean,hands?:string,damageType?:string,double?:boolean,armor?:number,dexCap?:number,checkPenalty?:number,spellFailure?:number};
export const equipmentCatalog=raw as Equipment[];
export const equipmentById=(id?:string)=>equipmentCatalog.find(e=>e.id===id);
const canonical=(s:string)=>s.toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(Boolean).sort().join(' ');
export const matchEquipment=(name:string,kind?:string)=>equipmentCatalog.find(e=>(!kind||e.kind===kind)&&canonical(e.name)===canonical(name));
function supplementalProficient(c:Character,e:Equipment){return c.classLevels.some(entry=>{
 const p=findClass(entry.classId)?.proficiencies;if(!p)return false;
 if(e.kind==='armor'){const armor=p.mediumAt&&entry.level>=p.mediumAt?'medium':p.armor;return ['none','light','medium','heavy'].indexOf(armor)>=['none','light','medium','heavy'].indexOf(e.category);}
 if(e.kind==='shield')return p.shields==='all'||(!e.name.includes('tower')&&(p.shields==='standard'||p.shields==='light'&&(/light/i.test(e.name)||e.name==='Buckler')));
 return p.weapons.includes(e.name)||e.category==='simple'&&p.simple&&(!p.simpleMeleeOnly||!e.ranged)||e.category==='martial'&&p.martial&&(!p.martialMeleeOnly||!e.ranged);
});}
export const allSizes=['Fine','Diminutive','Tiny','Small','Medium','Large','Huge','Gargantuan','Colossal'] as const;
export function scaleDice(dice:string,from:string,to:string){let n=allSizes.indexOf(to as Character['size'])-allSizes.indexOf(from as Character['size']);const up:Record<string,string>={'1':'1d2','1d2':'1d3','1d3':'1d4','1d4':'1d6','1d6':'1d8','1d8':'2d6','1d10':'2d8','1d12':'3d6','2d4':'2d6','2d6':'3d6','2d8':'3d8','2d10':'4d8','3d6':'4d6','3d8':'4d8','4d6':'6d6','4d8':'6d8','6d6':'8d6','6d8':'8d8','8d6':'12d6','8d8':'12d8','12d6':'16d6','12d8':'16d8'};const down:Record<string,string>={'1d2':'1','1d3':'1d2','1d4':'1d3','1d6':'1d4','1d8':'1d6','1d10':'1d8','1d12':'1d10','2d4':'1d6','2d6':'1d10','2d8':'2d6','2d10':'2d8','3d6':'2d6','3d8':'2d8','4d6':'3d6','4d8':'3d8','6d6':'4d6','6d8':'4d8','8d6':'6d6','8d8':'6d8','12d6':'8d6','12d8':'8d8','16d6':'12d6','16d8':'12d8'};while(n>0){dice=up[dice]||dice;n--}while(n<0){dice=down[dice]||dice;n++}return dice;}
export function armorProficient(c:Character,e:Equipment){if(supplementalProficient(c,e))return true;const ids=c.classLevels.map(e=>e.classId);if(e.kind==='shield'){if(e.name.includes('tower'))return ids.includes('fighter')||hasFeat(c,'Tower Shield Proficiency');return ids.some(x=>['factotum','barbarian','bard','cleric','druid','fighter','paladin','ranger','psychic-warrior','blackguard','dwarven-defender','arcane-archer','horizon-walker','war-mind'].includes(x))||hasFeat(c,'Shield Proficiency')}const rank=['light','medium','heavy'].indexOf(e.category);const trained=ids.some(x=>(['fighter','cleric','paladin','psychic-warrior','blackguard','dwarven-defender'].includes(x)?2:['barbarian','druid','arcane-archer','horizon-walker'].includes(x)?1:['factotum','bard','ranger','rogue','wilder','soulknife','assassin','war-mind'].includes(x)?0:-1)>=rank);return trained||hasFeat(c,'Armor Proficiency',e.category);}
export function weaponProficient(c:Character,w:Weapon){if(w.proficiency&&w.proficiency!=='auto')return w.proficiency==='yes';const e=equipmentById(w.catalogId);if(!e)return true;if(supplementalProficient(c,e))return true;const ids=c.classLevels.map(x=>x.classId);const martial=ids.some(x=>findClass(x)?.proficiencies?.martial&&!findClass(x)?.proficiencies?.martialMeleeOnly||['factotum','barbarian','fighter','paladin','ranger','psychic-warrior','blackguard','dwarven-defender','arcane-archer','horizon-walker','war-mind'].includes(x));if(e.category==='simple'&&ids.some(x=>['factotum','barbarian','bard','cleric','fighter','paladin','ranger','rogue','sorcerer','psion','psychic-warrior','soulknife','wilder','blackguard','dwarven-defender','arcane-archer','horizon-walker','war-mind'].includes(x)))return true;if(e.category==='martial'&&martial)return true;if((e.category==='simple'&&hasFeat(c,'Simple Weapon Proficiency')||hasFeat(c,e.category[0].toUpperCase()+e.category.slice(1)+' Weapon Proficiency',w.name)))return true;
 const r=racialTraits(c);if(r?.type.includes('(elf)')&&r.id!=='drow'&&['Longsword','Rapier','Longbow','Longbow, composite','Shortbow','Shortbow, composite'].includes(e.name))return true;if(r?.id==='drow'&&['Crossbow, hand','Rapier','Sword, short'].includes(e.name))return true;
 if(martial&&((r?.type.includes('dwarf')&&/dwarven/.test(e.name))||(r?.id.includes('gnome')&&/gnome/.test(e.name))))return true;
 const lists:Record<string,string[]>={wizard:['Club','Dagger','Crossbow, heavy','Crossbow, light','Quarterstaff'],druid:['Club','Dagger','Dart','Quarterstaff','Scimitar','Sickle','Shortspear','Sling','Spear'],monk:['Club','Crossbow, heavy','Crossbow, light','Dagger','Handaxe','Javelin','Kama','Nunchaku','Quarterstaff','Sai','Shuriken (5)','Siangham','Sling','Unarmed strike'],rogue:['Crossbow, hand','Rapier','Shortbow','Shortbow, composite','Sword, short'],bard:['Longsword','Rapier','Sap','Sword, short','Shortbow','Shortbow, composite','Whip']};return ids.some(id=>lists[id]?.includes(e.name))||e.name==='Unarmed strike';}
export function gearWeight(c:Character,g:Character['gear'][number]){const e=equipmentById(g.catalogId);if(!c.automation.enabled||!e)return g.weight;const index=allSizes.indexOf(c.size);const scale=e.kind==='weapon'?Math.pow(2,index-4):[.1,.1,.1,.5,1,2,5,8,12][index];return e.weight*scale*(g.material==='mithral'?.5:1);}
export function carriedWeight(c:Character){return c.gear.filter(g=>g.carried).reduce((n,g)=>n+g.qty*gearWeight(c,g),0)+(c.coinWeight?Object.values(c.coins).reduce((a,b)=>a+b,0)/50:0);}
const limits=[[0,0,0],[3,6,10],[6,13,20],[10,20,30],[13,26,40],[16,33,50],[20,40,60],[23,46,70],[26,53,80],[30,60,90],[33,66,100],[38,76,115],[43,86,130],[50,100,150],[58,116,175],[66,133,200],[76,153,230],[86,173,260],[100,200,300],[116,233,350],[133,266,400],[153,306,460],[173,346,520],[200,400,600],[233,466,700],[266,533,800],[306,613,920],[346,693,1040],[400,800,1200],[466,933,1400]];
export function carrying(c:Character){const str=Math.min(100,Math.max(0,Math.floor(effectiveScore(c,'STR')))),index=allSizes.indexOf(c.size),factor=(c.automation.quadruped?[.25,.5,.75,1,1.5,3,6,12,24]:[.125,.25,.5,.75,1,2,4,8,16])[index]*Math.pow(4,Math.max(0,Math.floor((str-20)/10)));const row=limits[str>29?20+str%10:str];const [light,medium,heavy]=row.map(v=>v*factor);const weight=carriedWeight(c);const category=weight<=light?'Light':weight<=medium?'Medium':weight<=heavy?'Heavy':weight<=heavy*2?'Overloaded':'Immobile';return {light,medium,heavy,lift:heavy*2,drag:heavy*5,weight,category,dexCap:category==='Light'?100:category==='Medium'?3:category==='Heavy'?1:0,checkPenalty:category==='Light'?0:category==='Medium'?-3:-6};}
export function equippedArmor(c:Character){const gear=c.gear.filter(g=>g.carried&&g.equipped&&g.qty>0&&['armor','shield'].includes(equipmentById(g.catalogId)?.kind||''));const selected=['armor','shield'].map(kind=>gear.filter(g=>equipmentById(g.catalogId)?.kind===kind).sort((a,b)=>(equipmentById(b.catalogId)!.armor!+(b.enhancement||0))-(equipmentById(a.catalogId)!.armor!+(a.enhancement||0)))[0]).filter(Boolean);
 let armor=0,shield=0,dexCap=100,checkPenalty=0,spellFailure=0,nonproficient=0,category=0,tower=0;
 for(const g of selected){const e=equipmentById(g.catalogId)!;const mithral=g.material==='mithral',cp=Math.min(0,e.checkPenalty!+(mithral?3:g.masterwork||g.enhancement||g.material==='adamantine'?1:0));if(e.kind==='armor'){armor=e.armor!+(g.enhancement||0);category=Math.max(1,['light','medium','heavy'].indexOf(e.category)+1-(mithral?1:0))}else{shield=e.armor!+(g.enhancement||0);if(e.name.includes('tower'))tower=-2;}dexCap=Math.min(dexCap,e.dexCap!+(mithral?2:0));checkPenalty+=cp;spellFailure+=Math.max(0,e.spellFailure!-(mithral?10:0));if(!(g.proficient??armorProficient(c,e)))nonproficient+=cp;}
 if(racialTraits(c)?.id==='warforged'){armor=Math.max(armor,2);spellFailure+=5;category=Math.max(category,1)}
 return {armor,shield,dexCap,checkPenalty,spellFailure:Math.min(100,spellFailure),category,nonproficient,tower,hasShield:shield>0,selected,multiple:gear.length>selected.length};}
export function movement(c:Character){const armor=equippedArmor(c),load=carrying(c),enc=c.automation.encumbrance;const monk=classLevel(c,'monk')+classLevel(c,'psionic-fist'),barb=classLevel(c,'barbarian');const free=armor.category===0&&!armor.hasShield&&(!enc||load.category==='Light');let speed=c.automation.baseSpeed+(barb&&armor.category<3&&(!enc||['Light','Medium'].includes(load.category))?10:0);const normal=speed;speed+=stackBonuses([{value:free?Math.floor(monk/3)*10:0,type:'enhancement',source:'monk'},...effectTerms(c,'speed.haste').map(t=>({...t,value:Math.min(normal,t.value)})),...effectTerms(c,'speed')]);speed=Math.max(0,speed);const dwarf=racialTraits(c)?.type.includes('dwarf');if(!dwarf&&(armor.category>=2||enc&&load.category!=='Light'))speed=Math.ceil(speed*2/3/5)*5;if(effectActive(c,'slow'))speed=Math.floor(speed/2/5)*5;for(const id of ['exhausted','entangled','blinded'])if(effectActive(c,id))speed=Math.floor(speed/2/5)*5;if(enc&&load.category==='Overloaded')speed=5;if(enc&&load.category==='Immobile')speed=0;const runMultiplier=armor.category===3||enc&&load.category==='Heavy'?(hasFeat(c,'Run')?4:3):(hasFeat(c,'Run')?5:4);speed=Math.min(10000,Math.max(0,Math.round(c.automation.overrides.speed??speed+(c.automation.adjustments.speed||0))));if(effectActive(c,'stunned')||effectActive(c,'prone'))speed=0;return {speed,free,run:effectActive(c,'slow')||effectActive(c,'blinded')||effectActive(c,'fatigued')||effectActive(c,'exhausted')||effectActive(c,'entangled')||enc&&['Overloaded','Immobile'].includes(load.category)?0:speed*runMultiplier};}
export function addEquipment(c:Character,e:Equipment){const id=crypto.randomUUID(),weaponId=e.kind==='weapon'?crypto.randomUUID():undefined;if(e.kind==='armor'||e.kind==='shield')for(const g of c.gear)if(equipmentById(g.catalogId)?.kind===e.kind)g.equipped=false;c.gear.push({id,name:e.name,catalogId:e.id,qty:1,weight:e.weight,carried:true,equipped:true,notes:'',enhancement:0,masterwork:false,material:'standard',weaponId});if(weaponId)c.weapons.push({id:weaponId,name:e.name,catalogId:e.id,ability:e.ranged?'DEX':'STR',attack:0,damage:e.damage!,damageAbility:e.ranged&&!e.thrown&&e.name!=='Sling'?'none':'STR',strength:e.hands==='two'&&!e.ranged?'two':'one',damageExtra:0,crit:`${e.threat===20?'20':e.threat+'–20'} / ×${e.multiplier}`,range:e.range?e.range+' ft.':'Melee',ammo:0,notes:e.double?'Primary end. Add a separate entry for the second end if used.':'',enhancement:0,proficiency:'auto',diceSize:'Medium',extraDamage:''});}
