"""Build revised-SRD race references and a small, original book-race summary catalog."""
import re,json,html,sys
from pathlib import Path
src=Path(sys.argv[1]);root=Path(__file__).resolve().parents[1]
def section(file,id):
 s=(src/file).read_text();hs=list(re.finditer(r'<h([1-6])\b[^>]*id="([^"]+)"[^>]*>.*?</h[1-6]>',s,re.S));m=next(x for x in hs if x[2]==id);end=next((x.start() for x in hs if x.start()>m.start() and int(x[1])<=int(m[1])),s.find('</body>'));return s[m.end():end]
def plain(s):
 s=re.sub(r'</(?:p|li|tr|h[1-6]|div|ul|table)>','\n\n',s);s=re.sub(r'</(?:td|th)>',' | ',s)
 return '\n\n'.join(re.sub(r'\s+',' ',html.unescape(re.sub('<[^>]+>',' ',x))).strip(' |') for x in s.split('\n\n') if re.sub('<[^>]+>','',x).strip())
def ref(file,id):
 folder='psionics' if file.startswith('psionic') else 'monsters' if file.startswith('monsters') else 'basic-rules-and-legal'
 return 'https://olimot.github.io/srd-v3.5/'+folder+'/'+file+'#'+id
races=[]
def add(id,name,group,file,anchor,**kw):
 r=dict(id=id,name=name,group=group,abilities={},size='Medium',speed=30,type='Humanoid',vision='Normal vision',languages=['Common'],bonusLanguages='See reference',favoredClass='Any',la=0,rhd=0,hitDice='None',natural=0,dodge=0,skills={},saves={},powerPoints=0,grapple=0,traits=[],source=ref(file,anchor),book='Revised 3.5 SRD',openGame=True,reference=plain(section(file,anchor)))
 r.update(kw);races.append(r);return r
def variant(id,name,base,file,anchor,**kw):
 parent=next(r for r in races if r['id']==base);r={**parent,'id':id,'name':name,'group':'Subraces','source':ref(file,anchor),'reference':'BASE RACE\n\n'+parent['reference']+'\n\nSUBRACE CHANGES\n\n'+plain(section(file,anchor))};r.update(kw);races.append(r);return r
f='races.html'
add('human','Human','Core',f,'humans',traits=['One bonus feat at 1st level. Allocate it in Feats.','Four extra skill points at 1st level and one at every later level. Spend these points manually.'])
add('dwarf','Dwarf','Core',f,'dwarves',abilities={'CON':2,'CHA':-2},speed=20,type='Humanoid (dwarf)',vision='Darkvision 60 ft.',languages=['Common','Dwarven'],favoredClass='Fighter',traits=['Stonecunning; dwarven weapon familiarity; stability while grounded.','Poison saves +2; saves against spells and spell-like effects +2. These conditional bonuses are entered for the relevant roll.','Attacks against orcs and goblinoids +1; dodge AC against giants +4. Stone/metal Appraise and Craft checks +2.','Armor and carried loads do not reduce the dwarf’s base land speed.'])
add('elf','Elf','Core',f,'elves',abilities={'DEX':2,'CON':-2},type='Humanoid (elf)',vision='Low-light vision',languages=['Common','Elven'],favoredClass='Wizard',skills={'Listen':2,'Search':2,'Spot':2},traits=['Immune to magical sleep; saves against enchantments +2.','Proficient with longsword, rapier, longbow, and shortbow, including composite bows.','Search check for secret or concealed doors passed within 5 feet.'])
add('gnome','Gnome','Core',f,'gnomes',abilities={'CON':2,'STR':-2},size='Small',speed=20,type='Humanoid (gnome)',vision='Low-light vision',languages=['Common','Gnome'],favoredClass='Bard',skills={'Listen':2,'Craft (alchemy)':2},traits=['Gnome hooked hammer familiarity. Illusion saves +2; illusion spell DCs +1.','Attacks against kobolds and goblinoids +1; dodge AC against giants +4.','Speak with burrowing mammals 1/day. With Charisma 10+, dancing lights, ghost sound, and prestidigitation each 1/day; caster level 1.'])
add('half-elf','Half-Elf','Core',f,'half-elves',type='Humanoid (elf)',vision='Low-light vision',languages=['Common','Elven'],skills={'Listen':1,'Search':1,'Spot':1,'Diplomacy':2,'Gather Information':2},traits=['Immune to magical sleep; enchantment saves +2.','Counts as an elf for race-related effects.'])
add('half-orc','Half-Orc','Core',f,'half-orcs',abilities={'STR':2,'INT':-2,'CHA':-2},type='Humanoid (orc)',vision='Darkvision 60 ft.',languages=['Common','Orc'],favoredClass='Barbarian',traits=['Counts as an orc for race-related effects. Starting Intelligence after the racial adjustment is at least 3.'])
add('halfling','Halfling','Core',f,'halflings',abilities={'DEX':2,'STR':-2},size='Small',speed=20,type='Humanoid (halfling)',languages=['Common','Halfling'],favoredClass='Rogue',skills={'Climb':2,'Jump':2,'Move Silently':2,'Listen':2},saves={'fort':1,'ref':1,'will':1},traits=['All saves +1. Against fear, add a further +2 morale bonus.','Thrown weapon and sling attacks +1. Use damage dice for Small weapons.'])
f='monsters-dr-dw.html'
variant('deep-dwarf','Deep Dwarf','dwarf',f,'deep-dwarf',vision='Darkvision 90 ft.',traits=['Dwarf traits, except poison and spell/spell-like saves increase to +3.','Light sensitivity: dazzled in bright sunlight or a daylight spell.'])
variant('mountain-dwarf','Mountain Dwarf','dwarf',f,'mountain-dwarf')
variant('duergar','Duergar','dwarf',f,'duergar',abilities={'CON':2,'CHA':-4},vision='Darkvision 120 ft.',languages=['Common','Dwarven','Undercommon'],la=1,skills={'Move Silently':4,'Listen':1,'Spot':1},traits=['Dwarf stonecunning, weapon familiarity, stability, and situational combat bonuses.','Immune to paralysis, phantasms, and poison; spell and spell-like saves +2.','Enlarge person and invisibility each 1/day; caster level twice class level, minimum 3. Check source restrictions.','Light sensitivity: dazzled in bright sunlight or daylight.'])
f='monsters-e-f.html'
variant('drow','Drow','elf',f,'drow',abilities={'DEX':2,'CON':-2,'INT':2,'CHA':2},vision='Darkvision 120 ft.',languages=['Common','Elven','Undercommon'],la=2,favoredClass='Wizard (male) / Cleric (female)',traits=['Elf sleep immunity, enchantment resistance, and senses. Spell resistance 11 + class levels.','Will saves against spells and spell-like abilities +2.','Dancing lights, darkness, and faerie fire each 1/day.','Hand crossbow, rapier, and short sword proficiency replace standard elf weapons.','Light blindness: blinded for the first round of abrupt bright light, then dazzled while exposed.'])
variant('aquatic-elf','Aquatic Elf','elf',f,'aquatic-elf',abilities={'DEX':2,'INT':-2},type='Humanoid (aquatic, elf)',vision='Superior low-light vision (4×)',favoredClass='Fighter',traits=['Elf traits with the aquatic subrace changes. Swim speed 40 ft.; aquatic breathing and swimming rules apply.','Superior low-light vision replaces ordinary low-light vision.'])
variant('gray-elf','Gray Elf','elf',f,'gray-elf',abilities={'STR':-2,'DEX':2,'CON':-2,'INT':2})
variant('wild-elf','Wild Elf','elf',f,'wild-elf',abilities={'DEX':2,'INT':-2},favoredClass='Sorcerer')
variant('wood-elf','Wood Elf','elf',f,'wood-elf',abilities={'STR':2,'DEX':2,'CON':-2,'INT':-2},favoredClass='Ranger')
f='monsters-g.html'
variant('deep-gnome','Deep Gnome (Svirfneblin)','gnome',f,'svirfneblin',abilities={'STR':-2,'DEX':2,'WIS':2,'CHA':-4},vision='Darkvision 120 ft.; low-light vision',la=3,dodge=4,saves={'fort':2,'ref':2,'will':2},skills={'Craft (alchemy)':2,'Listen':2,'Hide':2},languages=['Undercommon','Gnome','Common'],favoredClass='Rogue',traits=['All saves +2; dodge AC +4 against every opponent. Stonecunning.','Spell resistance 11 + class levels. Nondetection continuously; blindness/deafness, blur, and disguise self each 1/day.','Hide racial bonus +2, increasing to +4 underground. Illusion spell DCs +1. See reference for spell-like restrictions.'])
variant('forest-gnome','Forest Gnome','gnome',f,'forest-gnome',skills={'Listen':2,'Craft (alchemy)':2,'Hide':4},languages=['Gnome','Elven','Sylvan'],traits=['Gnome traits with forest subrace changes; pass without trace at will.','Hide racial bonus +4, increasing to +8 in woodland. Attacks against orcs and reptilian humanoids also gain +1.','Communicate simple messages with forest animals. Common must be selected as a bonus language.'])
add('gnoll','Gnoll','Monstrous',f,'gnolls-as-characters',abilities={'STR':4,'CON':2,'INT':-2,'CHA':-2},type='Humanoid (gnoll)',vision='Darkvision 60 ft.',languages=['Gnoll'],favoredClass='Ranger',la=1,rhd=2,hitDice='2d8 humanoid',natural=1,traits=['Racial HD contribute BAB +1, Fort +3, Ref +0, Will +0; add these to class totals manually.','Allocate racial skill points and one racial-HD feat from the source.'])
add('goblin','Goblin','Monstrous',f,'goblins-as-characters',abilities={'STR':-2,'DEX':2,'CHA':-2},size='Small',type='Humanoid (goblinoid)',vision='Darkvision 60 ft.',languages=['Common','Goblin'],favoredClass='Rogue',skills={'Move Silently':4,'Ride':4},traits=['Use Small weapon damage dice. The ordinary 1 humanoid HD is replaced by the first class level.'])
add('hobgoblin','Hobgoblin','Monstrous','monsters-h-i.html','hobgoblin-characters',abilities={'DEX':2,'CON':2},type='Humanoid (goblinoid)',vision='Darkvision 60 ft.',languages=['Common','Goblin'],favoredClass='Fighter',la=1,skills={'Move Silently':4},traits=['The ordinary 1 humanoid HD is replaced by the first class level.'])
f='monsters-k-l.html'
add('kobold','Kobold','Monstrous',f,'kobold-characters',abilities={'STR':-4,'DEX':2,'CON':-2},size='Small',type='Humanoid (reptilian)',vision='Darkvision 60 ft.',languages=['Draconic'],favoredClass='Sorcerer',natural=1,skills={'Craft (trapmaking)':2,'Profession (miner)':2,'Search':2},traits=['Light sensitivity: dazzled in bright sunlight or daylight.','Core Monster Manual kobold; optional web enhancements and dragonwrought changes are not included.'])
add('lizardfolk','Lizardfolk','Monstrous',f,'lizardfolk-as-characters',abilities={'STR':2,'CON':2,'INT':-2},type='Humanoid (reptilian)',languages=['Common','Draconic'],favoredClass='Druid',la=1,rhd=2,hitDice='2d8 humanoid',natural=5,skills={'Balance':4,'Jump':4,'Swim':4},traits=['Racial HD contribute BAB +1, Fort +0, Ref +3, Will +0; add these to class totals manually.','Two claws (1d4 each) and bite (1d4); add natural attacks in Combat.','Hold breath for 4 × Constitution score rounds. Allocate racial skill points and racial-HD feat manually.'])
f='monsters-o-r.html'
add('orc','Orc','Monstrous',f,'orcs-as-characters',abilities={'STR':4,'INT':-2,'WIS':-2,'CHA':-2},type='Humanoid (orc)',vision='Darkvision 60 ft.',languages=['Common','Orc'],favoredClass='Barbarian',traits=['Light sensitivity: dazzled in bright sunlight or daylight.'])
add('aasimar','Aasimar','Planetouched',f,'aasimar-as-characters',abilities={'WIS':2,'CHA':2},type='Outsider (native)',vision='Darkvision 60 ft.',languages=['Common','Celestial'],favoredClass='Paladin',la=1,skills={'Listen':2,'Spot':2},traits=['Acid, cold, and electricity resistance 5.','Daylight 1/day, caster level equal to class levels.'])
add('tiefling','Tiefling','Planetouched',f,'tieflings-as-characters',abilities={'DEX':2,'INT':2,'CHA':-2},type='Outsider (native)',vision='Darkvision 60 ft.',languages=['Common','Infernal'],favoredClass='Rogue',la=1,skills={'Bluff':2,'Hide':2},traits=['Cold, electricity, and fire resistance 5.','Darkness 1/day, caster level equal to class levels.'])
f='psionic-races.html'
add('dromite','Dromite','Psionic',f,'dromites',abilities={'CHA':2,'STR':-2,'WIS':-2},size='Small',speed=20,type='Monstrous humanoid (psionic)',vision='Normal vision; scent',favoredClass='Wilder',la=1,natural=3,powerPoints=1,skills={'Spot':2},traits=['Choose cold, electricity, fire, or sonic resistance 5.','Energy ray 1/day matching the chosen energy; manifester level half HD, minimum 1. Scent and Blind-Fight.'])
add('psionic-duergar','Duergar (Psionic)','Psionic',f,'duergar',abilities={'CON':2,'CHA':-4},speed=20,type='Humanoid (dwarf, psionic)',vision='Darkvision 120 ft.',languages=['Common','Dwarven','Undercommon'],favoredClass='Fighter',la=1,powerPoints=3,skills={'Move Silently':4,'Listen':1,'Spot':1},traits=['Psionic duergar variant. Dwarf stability, stonecunning, weapon familiarity, and situational bonuses.','Immune to paralysis, phantasms, and poison; light sensitivity.','Expansion and psionic invisibility each 1/day; manifester level equals Hit Dice, minimum 3.'])
add('elan','Elan','Psionic',f,'elans',abilities={'CHA':-2},type='Aberration (psionic)',favoredClass='Psion',powerPoints=2,traits=['Resistance: spend 1 PP as an immediate action for +4 saves until the next action.','Resilience: as an immediate action, spend PP to prevent 2 damage per point.','Repletion: spend 1 PP to avoid needing food or drink for 24 hours. No racial darkvision.'])
add('half-giant','Half-Giant','Psionic',f,'half-giants',abilities={'STR':2,'CON':2,'DEX':-2},type='Giant (psionic)',vision='Low-light vision',favoredClass='Psychic Warrior',la=1,powerPoints=2,grapple=4,traits=['Powerful build: treat as one size larger when advantageous for opposed size checks and size-limited attacks; use larger weapons. Space and reach stay Medium.','Fire saves +2. Stomp 1/day, manifester level half HD, minimum 1.'])
add('maenad','Maenad','Psionic',f,'maenads',type='Humanoid (maenad, psionic)',languages=['Common','Maenad'],favoredClass='Wilder',powerPoints=2,traits=['Sonic energy ray 1/day; manifester level half HD, minimum 1.','Outburst 1/day for up to 4 rounds: STR +2, INT −2, WIS −2. Enter temporary adjustments while active.'])
add('xeph','Xeph','Psionic',f,'xephs',abilities={'DEX':2,'STR':-2},type='Humanoid (xeph, psionic)',vision='Darkvision 60 ft.',languages=['Common','Xeph'],favoredClass='Soulknife',powerPoints=1,traits=['Saves against powers, spells, and spell-like effects +1.','Burst 3/day for 3 rounds: speed +10 ft., +20 ft. at level 5, +30 ft. at level 9.'])
# Book races contain original short summaries, not reproduced book passages.
def bookrace(id,name,book,source,**kw):
 r=dict(id=id,name=name,group='Other books',abilities={},size='Medium',speed=30,type='Humanoid',vision='Normal vision',languages=['Common'],bonusLanguages='See book',favoredClass='Any',la=0,rhd=0,hitDice='None',natural=0,dodge=0,skills={},saves={},powerPoints=0,grapple=0,traits=[],source=source,book=book,openGame=False,reference='');r.update(kw);races.append(r)
eberron='https://srd.dndtools.org/srd/races/racesEberron.html'
bookrace('changeling','Changeling','Eberron Campaign Setting',eberron,type='Humanoid (shapechanger)',favoredClass='Rogue',skills={'Bluff':2,'Intimidate':2,'Sense Motive':2},traits=['Sleep/charm saves +2. Speak Language is a class skill.','At-will physical disguise: full-round action, possessions unchanged, +10 Disguise when used. See book for limitations.'])
bookrace('warforged','Warforged','Eberron Campaign Setting',eberron,abilities={'CON':2,'WIS':-2,'CHA':-2},type='Construct (living construct)',favoredClass='Fighter',traits=['Composite plating: armor +2, arcane failure 5%; enter in Combat. Does not stack with armor.','Light fortification 25%; slam 1d4.','No eating, breathing, or sleeping. Ordinary healing works at half strength; lethal damage does not heal naturally.','Immune to poison, sleep, paralysis, disease, nausea, fatigue, exhaustion, sickening, and energy drain. Consult living-construct exceptions.'])
stone='https://srd.dndtools.org/srd/races/racesRos.html'
bookrace('goliath','Goliath','Races of Stone',stone,abilities={'STR':4,'DEX':-2,'CON':2},type='Monstrous humanoid',favoredClass='Barbarian',languages=['Common','Gol-Kaa'],la=1,grapple=4,skills={'Sense Motive':2},traits=['Powerful build permits larger weapons and favorable size treatment for opposed checks; actual size and reach stay Medium.','Standing jumps count as running jumps; accelerated climbing avoids its usual penalty. Acclimated to high altitude.'])
bookrace('whisper-gnome','Whisper Gnome','Races of Stone',stone,abilities={'DEX':2,'CON':2,'STR':-2,'CHA':-2},size='Small',type='Humanoid (gnome)',vision='Darkvision 60 ft.; low-light vision',languages=['Common','Gnome'],favoredClass='Rogue',skills={'Hide':4,'Move Silently':4,'Listen':2,'Spot':2},traits=['Hooked-hammer familiarity. Attacks against kobolds/goblinoids +1; dodge AC against giants +4.','Silence centered on self 1/day. With CHA 10+, ghost sound, mage hand, and message each 1/day; caster level 1.'])
for r in races:
 if r['openGame']:
  m=re.search(r'Bonus Languages?:\s*(.*?)(?:\n\n|$)',r['reference'])
  if m:r['bonusLanguages']=m[1].strip()
assert len(races)==35,len(races)
assert len(set(r['id'] for r in races))==len(races)
(root/'lib/race-data.json').write_text(json.dumps([{k:v for k,v in r.items() if k!='reference'} for r in races],ensure_ascii=False,separators=(',',':')))
(root/'public/data/races.json').write_text(json.dumps(races,ensure_ascii=False,separators=(',',':')))
print(json.dumps({'races':len(races),'core':sum(r['group']=='Core' for r in races),'srd':sum(r['openGame'] for r in races)}))
